-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity delta_encoding is
generic (
    C_M_AXI_GMEM_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_GMEM_ID_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_GMEM_BUSER_WIDTH : INTEGER := 1;
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_GMEM_USER_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_PROT_VALUE : INTEGER := 0;
    C_M_AXI_GMEM_CACHE_VALUE : INTEGER := 3 );
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    m_axi_gmem_AWVALID : OUT STD_LOGIC;
    m_axi_gmem_AWREADY : IN STD_LOGIC;
    m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_AWUSER_WIDTH-1 downto 0);
    m_axi_gmem_WVALID : OUT STD_LOGIC;
    m_axi_gmem_WREADY : IN STD_LOGIC;
    m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH-1 downto 0);
    m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH/8-1 downto 0);
    m_axi_gmem_WLAST : OUT STD_LOGIC;
    m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_WUSER_WIDTH-1 downto 0);
    m_axi_gmem_ARVALID : OUT STD_LOGIC;
    m_axi_gmem_ARREADY : IN STD_LOGIC;
    m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ADDR_WIDTH-1 downto 0);
    m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_GMEM_ARUSER_WIDTH-1 downto 0);
    m_axi_gmem_RVALID : IN STD_LOGIC;
    m_axi_gmem_RREADY : OUT STD_LOGIC;
    m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_DATA_WIDTH-1 downto 0);
    m_axi_gmem_RLAST : IN STD_LOGIC;
    m_axi_gmem_RID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_RUSER_WIDTH-1 downto 0);
    m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BVALID : IN STD_LOGIC;
    m_axi_gmem_BREADY : OUT STD_LOGIC;
    m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_gmem_BID : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_ID_WIDTH-1 downto 0);
    m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_GMEM_BUSER_WIDTH-1 downto 0);
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    interrupt : OUT STD_LOGIC );
end;


architecture behav of delta_encoding is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "delta_encoding_delta_encoding,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=1,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=59612,HLS_SYN_TPT=none,HLS_SYN_MEM=12,HLS_SYN_DSP=0,HLS_SYN_FF=3316,HLS_SYN_LUT=4194,HLS_VERSION=2024_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant C_M_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_start : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_ready : STD_LOGIC;
    signal img : STD_LOGIC_VECTOR (63 downto 0);
    signal spikes : STD_LOGIC_VECTOR (63 downto 0);
    signal threshold : STD_LOGIC_VECTOR (31 downto 0);
    signal leak : STD_LOGIC_VECTOR (31 downto 0);
    signal leak_read_reg_228 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal threshold_read_reg_233 : STD_LOGIC_VECTOR (31 downto 0);
    signal spikes_read_reg_238 : STD_LOGIC_VECTOR (63 downto 0);
    signal empty_fu_180_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal empty_reg_243 : STD_LOGIC_VECTOR (30 downto 0);
    signal empty_34_fu_185_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal empty_34_reg_248 : STD_LOGIC_VECTOR (22 downto 0);
    signal sub1_fu_212_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub1_reg_253 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_cast_reg_258 : STD_LOGIC_VECTOR (61 downto 0);
    signal integrator_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal integrator_ce0 : STD_LOGIC;
    signal integrator_we0 : STD_LOGIC;
    signal integrator_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal integrator_ce1 : STD_LOGIC;
    signal integrator_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal integrator_1_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal integrator_1_ce0 : STD_LOGIC;
    signal integrator_1_we0 : STD_LOGIC;
    signal integrator_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal integrator_1_ce1 : STD_LOGIC;
    signal integrator_1_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal integrator_2_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal integrator_2_ce0 : STD_LOGIC;
    signal integrator_2_we0 : STD_LOGIC;
    signal integrator_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal integrator_2_ce1 : STD_LOGIC;
    signal integrator_2_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal integrator_3_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal integrator_3_ce0 : STD_LOGIC;
    signal integrator_3_we0 : STD_LOGIC;
    signal integrator_3_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal integrator_3_ce1 : STD_LOGIC;
    signal integrator_3_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal integrator_4_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal integrator_4_ce0 : STD_LOGIC;
    signal integrator_4_we0 : STD_LOGIC;
    signal integrator_4_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal integrator_4_ce1 : STD_LOGIC;
    signal integrator_4_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal integrator_5_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal integrator_5_ce0 : STD_LOGIC;
    signal integrator_5_we0 : STD_LOGIC;
    signal integrator_5_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal integrator_5_ce1 : STD_LOGIC;
    signal integrator_5_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal integrator_6_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal integrator_6_ce0 : STD_LOGIC;
    signal integrator_6_we0 : STD_LOGIC;
    signal integrator_6_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal integrator_6_ce1 : STD_LOGIC;
    signal integrator_6_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal integrator_7_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal integrator_7_ce0 : STD_LOGIC;
    signal integrator_7_we0 : STD_LOGIC;
    signal integrator_7_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal integrator_7_ce1 : STD_LOGIC;
    signal integrator_7_q1 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_ap_start : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_ap_done : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_ap_idle : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_ap_ready : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_7_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_7_ce0 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_7_we0 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_7_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_6_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_6_ce0 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_6_we0 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_6_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_5_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_5_ce0 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_5_we0 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_5_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_4_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_4_ce0 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_4_we0 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_4_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_3_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_3_ce0 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_3_we0 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_3_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_2_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_2_ce0 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_2_we0 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_1_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_1_ce0 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_1_we0 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_ce0 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_we0 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_ap_start : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_ap_done : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_ap_idle : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_ap_ready : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_AWVALID : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_WVALID : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_WLAST : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_ARVALID : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_RREADY : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_BREADY : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_ce0 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_we0 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_ce1 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_1_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_1_ce0 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_1_we0 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_1_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_1_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_1_ce1 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_2_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_2_ce0 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_2_we0 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_2_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_2_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_2_ce1 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_3_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_3_ce0 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_3_we0 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_3_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_3_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_3_ce1 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_4_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_4_ce0 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_4_we0 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_4_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_4_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_4_ce1 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_5_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_5_ce0 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_5_we0 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_5_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_5_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_5_ce1 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_6_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_6_ce0 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_6_we0 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_6_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_6_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_6_ce1 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_7_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_7_ce0 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_7_we0 : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_7_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_7_address1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_7_ce1 : STD_LOGIC;
    signal gmem_AWVALID : STD_LOGIC;
    signal gmem_AWREADY : STD_LOGIC;
    signal gmem_WVALID : STD_LOGIC;
    signal gmem_WREADY : STD_LOGIC;
    signal gmem_ARVALID : STD_LOGIC;
    signal gmem_ARREADY : STD_LOGIC;
    signal gmem_RVALID : STD_LOGIC;
    signal gmem_RREADY : STD_LOGIC;
    signal gmem_RDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal gmem_RFIFONUM : STD_LOGIC_VECTOR (8 downto 0);
    signal gmem_BVALID : STD_LOGIC;
    signal gmem_BREADY : STD_LOGIC;
    signal grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal sub1_to_int_fu_176_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal bit_sel_fu_190_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_val_fu_198_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sub1_neg_fu_204_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component delta_encoding_delta_encoding_Pipeline_INIT_LOOP IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        integrator_7_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        integrator_7_ce0 : OUT STD_LOGIC;
        integrator_7_we0 : OUT STD_LOGIC;
        integrator_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        integrator_6_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        integrator_6_ce0 : OUT STD_LOGIC;
        integrator_6_we0 : OUT STD_LOGIC;
        integrator_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        integrator_5_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        integrator_5_ce0 : OUT STD_LOGIC;
        integrator_5_we0 : OUT STD_LOGIC;
        integrator_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        integrator_4_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        integrator_4_ce0 : OUT STD_LOGIC;
        integrator_4_we0 : OUT STD_LOGIC;
        integrator_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        integrator_3_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        integrator_3_ce0 : OUT STD_LOGIC;
        integrator_3_we0 : OUT STD_LOGIC;
        integrator_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        integrator_2_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        integrator_2_ce0 : OUT STD_LOGIC;
        integrator_2_we0 : OUT STD_LOGIC;
        integrator_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        integrator_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        integrator_1_ce0 : OUT STD_LOGIC;
        integrator_1_we0 : OUT STD_LOGIC;
        integrator_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        integrator_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        integrator_ce0 : OUT STD_LOGIC;
        integrator_we0 : OUT STD_LOGIC;
        integrator_d0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component delta_encoding_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_gmem_AWVALID : OUT STD_LOGIC;
        m_axi_gmem_AWREADY : IN STD_LOGIC;
        m_axi_gmem_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_WVALID : OUT STD_LOGIC;
        m_axi_gmem_WREADY : IN STD_LOGIC;
        m_axi_gmem_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_WLAST : OUT STD_LOGIC;
        m_axi_gmem_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_ARVALID : OUT STD_LOGIC;
        m_axi_gmem_ARREADY : IN STD_LOGIC;
        m_axi_gmem_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_gmem_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_gmem_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_gmem_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RVALID : IN STD_LOGIC;
        m_axi_gmem_RREADY : OUT STD_LOGIC;
        m_axi_gmem_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_gmem_RLAST : IN STD_LOGIC;
        m_axi_gmem_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_gmem_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_BVALID : IN STD_LOGIC;
        m_axi_gmem_BREADY : OUT STD_LOGIC;
        m_axi_gmem_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_gmem_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_gmem_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        threshold : IN STD_LOGIC_VECTOR (31 downto 0);
        sub1_to_int : IN STD_LOGIC_VECTOR (30 downto 0);
        empty : IN STD_LOGIC_VECTOR (22 downto 0);
        spikes : IN STD_LOGIC_VECTOR (63 downto 0);
        integrator_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        integrator_ce0 : OUT STD_LOGIC;
        integrator_we0 : OUT STD_LOGIC;
        integrator_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        integrator_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        integrator_ce1 : OUT STD_LOGIC;
        integrator_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        integrator_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        integrator_1_ce0 : OUT STD_LOGIC;
        integrator_1_we0 : OUT STD_LOGIC;
        integrator_1_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        integrator_1_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        integrator_1_ce1 : OUT STD_LOGIC;
        integrator_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        integrator_2_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        integrator_2_ce0 : OUT STD_LOGIC;
        integrator_2_we0 : OUT STD_LOGIC;
        integrator_2_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        integrator_2_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        integrator_2_ce1 : OUT STD_LOGIC;
        integrator_2_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        integrator_3_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        integrator_3_ce0 : OUT STD_LOGIC;
        integrator_3_we0 : OUT STD_LOGIC;
        integrator_3_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        integrator_3_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        integrator_3_ce1 : OUT STD_LOGIC;
        integrator_3_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        integrator_4_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        integrator_4_ce0 : OUT STD_LOGIC;
        integrator_4_we0 : OUT STD_LOGIC;
        integrator_4_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        integrator_4_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        integrator_4_ce1 : OUT STD_LOGIC;
        integrator_4_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        integrator_5_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        integrator_5_ce0 : OUT STD_LOGIC;
        integrator_5_we0 : OUT STD_LOGIC;
        integrator_5_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        integrator_5_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        integrator_5_ce1 : OUT STD_LOGIC;
        integrator_5_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        integrator_6_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        integrator_6_ce0 : OUT STD_LOGIC;
        integrator_6_we0 : OUT STD_LOGIC;
        integrator_6_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        integrator_6_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        integrator_6_ce1 : OUT STD_LOGIC;
        integrator_6_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        integrator_7_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        integrator_7_ce0 : OUT STD_LOGIC;
        integrator_7_we0 : OUT STD_LOGIC;
        integrator_7_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        integrator_7_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
        integrator_7_ce1 : OUT STD_LOGIC;
        integrator_7_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        leak : IN STD_LOGIC_VECTOR (31 downto 0);
        p_cast_cast : IN STD_LOGIC_VECTOR (61 downto 0);
        sub1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component delta_encoding_integrator_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        address1 : IN STD_LOGIC_VECTOR (6 downto 0);
        ce1 : IN STD_LOGIC;
        q1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component delta_encoding_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        img : OUT STD_LOGIC_VECTOR (63 downto 0);
        spikes : OUT STD_LOGIC_VECTOR (63 downto 0);
        threshold : OUT STD_LOGIC_VECTOR (31 downto 0);
        leak : OUT STD_LOGIC_VECTOR (31 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component delta_encoding_gmem_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_MAXREQS : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER;
        CH0_USER_RFIFONUM_WIDTH : INTEGER;
        CH0_USER_DW : INTEGER;
        CH0_USER_AW : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_CH0_ARVALID : IN STD_LOGIC;
        I_CH0_ARREADY : OUT STD_LOGIC;
        I_CH0_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RVALID : OUT STD_LOGIC;
        I_CH0_RREADY : IN STD_LOGIC;
        I_CH0_RDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RFIFONUM : OUT STD_LOGIC_VECTOR (8 downto 0);
        I_CH0_AWVALID : IN STD_LOGIC;
        I_CH0_AWREADY : OUT STD_LOGIC;
        I_CH0_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WVALID : IN STD_LOGIC;
        I_CH0_WREADY : OUT STD_LOGIC;
        I_CH0_WDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        I_CH0_BVALID : OUT STD_LOGIC;
        I_CH0_BREADY : IN STD_LOGIC );
    end component;



begin
    integrator_U : component delta_encoding_integrator_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 98,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => integrator_address0,
        ce0 => integrator_ce0,
        we0 => integrator_we0,
        d0 => integrator_d0,
        address1 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_address1,
        ce1 => integrator_ce1,
        q1 => integrator_q1);

    integrator_1_U : component delta_encoding_integrator_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 98,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => integrator_1_address0,
        ce0 => integrator_1_ce0,
        we0 => integrator_1_we0,
        d0 => integrator_1_d0,
        address1 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_1_address1,
        ce1 => integrator_1_ce1,
        q1 => integrator_1_q1);

    integrator_2_U : component delta_encoding_integrator_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 98,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => integrator_2_address0,
        ce0 => integrator_2_ce0,
        we0 => integrator_2_we0,
        d0 => integrator_2_d0,
        address1 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_2_address1,
        ce1 => integrator_2_ce1,
        q1 => integrator_2_q1);

    integrator_3_U : component delta_encoding_integrator_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 98,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => integrator_3_address0,
        ce0 => integrator_3_ce0,
        we0 => integrator_3_we0,
        d0 => integrator_3_d0,
        address1 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_3_address1,
        ce1 => integrator_3_ce1,
        q1 => integrator_3_q1);

    integrator_4_U : component delta_encoding_integrator_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 98,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => integrator_4_address0,
        ce0 => integrator_4_ce0,
        we0 => integrator_4_we0,
        d0 => integrator_4_d0,
        address1 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_4_address1,
        ce1 => integrator_4_ce1,
        q1 => integrator_4_q1);

    integrator_5_U : component delta_encoding_integrator_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 98,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => integrator_5_address0,
        ce0 => integrator_5_ce0,
        we0 => integrator_5_we0,
        d0 => integrator_5_d0,
        address1 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_5_address1,
        ce1 => integrator_5_ce1,
        q1 => integrator_5_q1);

    integrator_6_U : component delta_encoding_integrator_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 98,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => integrator_6_address0,
        ce0 => integrator_6_ce0,
        we0 => integrator_6_we0,
        d0 => integrator_6_d0,
        address1 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_6_address1,
        ce1 => integrator_6_ce1,
        q1 => integrator_6_q1);

    integrator_7_U : component delta_encoding_integrator_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 98,
        AddressWidth => 7)
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        address0 => integrator_7_address0,
        ce0 => integrator_7_ce0,
        we0 => integrator_7_we0,
        d0 => integrator_7_d0,
        address1 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_7_address1,
        ce1 => integrator_7_ce1,
        q1 => integrator_7_q1);

    grp_delta_encoding_Pipeline_INIT_LOOP_fu_132 : component delta_encoding_delta_encoding_Pipeline_INIT_LOOP
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_ap_start,
        ap_done => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_ap_done,
        ap_idle => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_ap_idle,
        ap_ready => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_ap_ready,
        integrator_7_address0 => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_7_address0,
        integrator_7_ce0 => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_7_ce0,
        integrator_7_we0 => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_7_we0,
        integrator_7_d0 => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_7_d0,
        integrator_6_address0 => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_6_address0,
        integrator_6_ce0 => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_6_ce0,
        integrator_6_we0 => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_6_we0,
        integrator_6_d0 => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_6_d0,
        integrator_5_address0 => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_5_address0,
        integrator_5_ce0 => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_5_ce0,
        integrator_5_we0 => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_5_we0,
        integrator_5_d0 => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_5_d0,
        integrator_4_address0 => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_4_address0,
        integrator_4_ce0 => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_4_ce0,
        integrator_4_we0 => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_4_we0,
        integrator_4_d0 => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_4_d0,
        integrator_3_address0 => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_3_address0,
        integrator_3_ce0 => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_3_ce0,
        integrator_3_we0 => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_3_we0,
        integrator_3_d0 => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_3_d0,
        integrator_2_address0 => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_2_address0,
        integrator_2_ce0 => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_2_ce0,
        integrator_2_we0 => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_2_we0,
        integrator_2_d0 => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_2_d0,
        integrator_1_address0 => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_1_address0,
        integrator_1_ce0 => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_1_ce0,
        integrator_1_we0 => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_1_we0,
        integrator_1_d0 => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_1_d0,
        integrator_address0 => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_address0,
        integrator_ce0 => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_ce0,
        integrator_we0 => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_we0,
        integrator_d0 => grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_d0);

    grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152 : component delta_encoding_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_ap_start,
        ap_done => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_ap_done,
        ap_idle => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_ap_idle,
        ap_ready => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_ap_ready,
        m_axi_gmem_AWVALID => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY => gmem_AWREADY,
        m_axi_gmem_AWADDR => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_AWADDR,
        m_axi_gmem_AWID => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_AWID,
        m_axi_gmem_AWLEN => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_WVALID,
        m_axi_gmem_WREADY => gmem_WREADY,
        m_axi_gmem_WDATA => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_WLAST,
        m_axi_gmem_WID => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_WID,
        m_axi_gmem_WUSER => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY => gmem_ARREADY,
        m_axi_gmem_ARADDR => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_ARADDR,
        m_axi_gmem_ARID => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_ARID,
        m_axi_gmem_ARLEN => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID => gmem_RVALID,
        m_axi_gmem_RREADY => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_RREADY,
        m_axi_gmem_RDATA => gmem_RDATA,
        m_axi_gmem_RLAST => ap_const_logic_0,
        m_axi_gmem_RID => ap_const_lv1_0,
        m_axi_gmem_RFIFONUM => gmem_RFIFONUM,
        m_axi_gmem_RUSER => ap_const_lv1_0,
        m_axi_gmem_RRESP => ap_const_lv2_0,
        m_axi_gmem_BVALID => gmem_BVALID,
        m_axi_gmem_BREADY => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_BREADY,
        m_axi_gmem_BRESP => ap_const_lv2_0,
        m_axi_gmem_BID => ap_const_lv1_0,
        m_axi_gmem_BUSER => ap_const_lv1_0,
        threshold => threshold_read_reg_233,
        sub1_to_int => empty_reg_243,
        empty => empty_34_reg_248,
        spikes => spikes_read_reg_238,
        integrator_address0 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_address0,
        integrator_ce0 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_ce0,
        integrator_we0 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_we0,
        integrator_d0 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_d0,
        integrator_address1 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_address1,
        integrator_ce1 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_ce1,
        integrator_q1 => integrator_q1,
        integrator_1_address0 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_1_address0,
        integrator_1_ce0 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_1_ce0,
        integrator_1_we0 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_1_we0,
        integrator_1_d0 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_1_d0,
        integrator_1_address1 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_1_address1,
        integrator_1_ce1 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_1_ce1,
        integrator_1_q1 => integrator_1_q1,
        integrator_2_address0 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_2_address0,
        integrator_2_ce0 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_2_ce0,
        integrator_2_we0 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_2_we0,
        integrator_2_d0 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_2_d0,
        integrator_2_address1 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_2_address1,
        integrator_2_ce1 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_2_ce1,
        integrator_2_q1 => integrator_2_q1,
        integrator_3_address0 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_3_address0,
        integrator_3_ce0 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_3_ce0,
        integrator_3_we0 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_3_we0,
        integrator_3_d0 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_3_d0,
        integrator_3_address1 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_3_address1,
        integrator_3_ce1 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_3_ce1,
        integrator_3_q1 => integrator_3_q1,
        integrator_4_address0 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_4_address0,
        integrator_4_ce0 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_4_ce0,
        integrator_4_we0 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_4_we0,
        integrator_4_d0 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_4_d0,
        integrator_4_address1 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_4_address1,
        integrator_4_ce1 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_4_ce1,
        integrator_4_q1 => integrator_4_q1,
        integrator_5_address0 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_5_address0,
        integrator_5_ce0 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_5_ce0,
        integrator_5_we0 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_5_we0,
        integrator_5_d0 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_5_d0,
        integrator_5_address1 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_5_address1,
        integrator_5_ce1 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_5_ce1,
        integrator_5_q1 => integrator_5_q1,
        integrator_6_address0 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_6_address0,
        integrator_6_ce0 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_6_ce0,
        integrator_6_we0 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_6_we0,
        integrator_6_d0 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_6_d0,
        integrator_6_address1 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_6_address1,
        integrator_6_ce1 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_6_ce1,
        integrator_6_q1 => integrator_6_q1,
        integrator_7_address0 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_7_address0,
        integrator_7_ce0 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_7_ce0,
        integrator_7_we0 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_7_we0,
        integrator_7_d0 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_7_d0,
        integrator_7_address1 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_7_address1,
        integrator_7_ce1 => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_7_ce1,
        integrator_7_q1 => integrator_7_q1,
        leak => leak_read_reg_228,
        p_cast_cast => p_cast_reg_258,
        sub1 => sub1_reg_253);

    control_s_axi_U : component delta_encoding_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        img => img,
        spikes => spikes,
        threshold => threshold,
        leak => leak,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    gmem_m_axi_U : component delta_encoding_gmem_m_axi
    generic map (
        CONSERVATIVE => 1,
        USER_MAXREQS => 7,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_GMEM_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_GMEM_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_GMEM_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_GMEM_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_GMEM_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_GMEM_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_GMEM_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_GMEM_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_GMEM_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_GMEM_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_GMEM_CACHE_VALUE,
        CH0_USER_RFIFONUM_WIDTH => 9,
        CH0_USER_DW => 32,
        CH0_USER_AW => 64,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 16)
    port map (
        AWVALID => m_axi_gmem_AWVALID,
        AWREADY => m_axi_gmem_AWREADY,
        AWADDR => m_axi_gmem_AWADDR,
        AWID => m_axi_gmem_AWID,
        AWLEN => m_axi_gmem_AWLEN,
        AWSIZE => m_axi_gmem_AWSIZE,
        AWBURST => m_axi_gmem_AWBURST,
        AWLOCK => m_axi_gmem_AWLOCK,
        AWCACHE => m_axi_gmem_AWCACHE,
        AWPROT => m_axi_gmem_AWPROT,
        AWQOS => m_axi_gmem_AWQOS,
        AWREGION => m_axi_gmem_AWREGION,
        AWUSER => m_axi_gmem_AWUSER,
        WVALID => m_axi_gmem_WVALID,
        WREADY => m_axi_gmem_WREADY,
        WDATA => m_axi_gmem_WDATA,
        WSTRB => m_axi_gmem_WSTRB,
        WLAST => m_axi_gmem_WLAST,
        WID => m_axi_gmem_WID,
        WUSER => m_axi_gmem_WUSER,
        ARVALID => m_axi_gmem_ARVALID,
        ARREADY => m_axi_gmem_ARREADY,
        ARADDR => m_axi_gmem_ARADDR,
        ARID => m_axi_gmem_ARID,
        ARLEN => m_axi_gmem_ARLEN,
        ARSIZE => m_axi_gmem_ARSIZE,
        ARBURST => m_axi_gmem_ARBURST,
        ARLOCK => m_axi_gmem_ARLOCK,
        ARCACHE => m_axi_gmem_ARCACHE,
        ARPROT => m_axi_gmem_ARPROT,
        ARQOS => m_axi_gmem_ARQOS,
        ARREGION => m_axi_gmem_ARREGION,
        ARUSER => m_axi_gmem_ARUSER,
        RVALID => m_axi_gmem_RVALID,
        RREADY => m_axi_gmem_RREADY,
        RDATA => m_axi_gmem_RDATA,
        RLAST => m_axi_gmem_RLAST,
        RID => m_axi_gmem_RID,
        RUSER => m_axi_gmem_RUSER,
        RRESP => m_axi_gmem_RRESP,
        BVALID => m_axi_gmem_BVALID,
        BREADY => m_axi_gmem_BREADY,
        BRESP => m_axi_gmem_BRESP,
        BID => m_axi_gmem_BID,
        BUSER => m_axi_gmem_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_CH0_ARVALID => gmem_ARVALID,
        I_CH0_ARREADY => gmem_ARREADY,
        I_CH0_ARADDR => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_ARADDR,
        I_CH0_ARLEN => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_ARLEN,
        I_CH0_RVALID => gmem_RVALID,
        I_CH0_RREADY => gmem_RREADY,
        I_CH0_RDATA => gmem_RDATA,
        I_CH0_RFIFONUM => gmem_RFIFONUM,
        I_CH0_AWVALID => gmem_AWVALID,
        I_CH0_AWREADY => gmem_AWREADY,
        I_CH0_AWADDR => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_AWADDR,
        I_CH0_AWLEN => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_AWLEN,
        I_CH0_WVALID => gmem_WVALID,
        I_CH0_WREADY => gmem_WREADY,
        I_CH0_WDATA => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_WDATA,
        I_CH0_WSTRB => grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_WSTRB,
        I_CH0_BVALID => gmem_BVALID,
        I_CH0_BREADY => gmem_BREADY);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_ap_ready = ap_const_logic_1)) then 
                    grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                    grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_ap_ready = ap_const_logic_1)) then 
                    grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                empty_34_reg_248 <= empty_34_fu_185_p1;
                empty_reg_243 <= empty_fu_180_p1;
                leak_read_reg_228 <= leak;
                p_cast_reg_258 <= img(63 downto 2);
                spikes_read_reg_238 <= spikes;
                sub1_reg_253 <= sub1_fu_212_p1;
                threshold_read_reg_233 <= threshold;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_ap_done, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_ap_done, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_ap_done)
    begin
        if ((grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_ap_done)
    begin
        if ((grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_ap_done, ap_CS_fsm_state4)
    begin
        if (((grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_ap_done, ap_CS_fsm_state4)
    begin
        if (((grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    bit_sel_fu_190_p3 <= sub1_to_int_fu_176_p1(31 downto 31);
    empty_34_fu_185_p1 <= sub1_to_int_fu_176_p1(23 - 1 downto 0);
    empty_fu_180_p1 <= sub1_to_int_fu_176_p1(31 - 1 downto 0);

    gmem_ARVALID_assign_proc : process(ap_CS_fsm_state3, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_ARVALID, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            gmem_ARVALID <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_ARVALID;
        else 
            gmem_ARVALID <= ap_const_logic_0;
        end if; 
    end process;


    gmem_AWVALID_assign_proc : process(ap_CS_fsm_state3, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_AWVALID, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            gmem_AWVALID <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_AWVALID;
        else 
            gmem_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    gmem_BREADY_assign_proc : process(ap_CS_fsm_state3, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_BREADY, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            gmem_BREADY <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_BREADY;
        else 
            gmem_BREADY <= ap_const_logic_0;
        end if; 
    end process;


    gmem_RREADY_assign_proc : process(ap_CS_fsm_state3, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_RREADY, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            gmem_RREADY <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_RREADY;
        else 
            gmem_RREADY <= ap_const_logic_0;
        end if; 
    end process;


    gmem_WVALID_assign_proc : process(ap_CS_fsm_state3, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_WVALID, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state4))) then 
            gmem_WVALID <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_m_axi_gmem_WVALID;
        else 
            gmem_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_ap_start <= grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_ap_start_reg;
    grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_ap_start <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_ap_start_reg;

    integrator_1_address0_assign_proc : process(grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_1_address0, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_1_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_1_address0 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_1_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            integrator_1_address0 <= grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_1_address0;
        else 
            integrator_1_address0 <= "XXXXXXX";
        end if; 
    end process;


    integrator_1_ce0_assign_proc : process(grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_1_ce0, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_1_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_1_ce0 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_1_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            integrator_1_ce0 <= grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_1_ce0;
        else 
            integrator_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    integrator_1_ce1_assign_proc : process(grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_1_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_1_ce1 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_1_ce1;
        else 
            integrator_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    integrator_1_d0_assign_proc : process(grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_1_d0, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_1_d0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_1_d0 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_1_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            integrator_1_d0 <= grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_1_d0;
        else 
            integrator_1_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    integrator_1_we0_assign_proc : process(grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_1_we0, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_1_we0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_1_we0 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_1_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            integrator_1_we0 <= grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_1_we0;
        else 
            integrator_1_we0 <= ap_const_logic_0;
        end if; 
    end process;


    integrator_2_address0_assign_proc : process(grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_2_address0, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_2_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_2_address0 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_2_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            integrator_2_address0 <= grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_2_address0;
        else 
            integrator_2_address0 <= "XXXXXXX";
        end if; 
    end process;


    integrator_2_ce0_assign_proc : process(grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_2_ce0, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_2_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_2_ce0 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_2_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            integrator_2_ce0 <= grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_2_ce0;
        else 
            integrator_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    integrator_2_ce1_assign_proc : process(grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_2_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_2_ce1 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_2_ce1;
        else 
            integrator_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    integrator_2_d0_assign_proc : process(grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_2_d0, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_2_d0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_2_d0 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_2_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            integrator_2_d0 <= grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_2_d0;
        else 
            integrator_2_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    integrator_2_we0_assign_proc : process(grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_2_we0, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_2_we0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_2_we0 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_2_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            integrator_2_we0 <= grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_2_we0;
        else 
            integrator_2_we0 <= ap_const_logic_0;
        end if; 
    end process;


    integrator_3_address0_assign_proc : process(grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_3_address0, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_3_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_3_address0 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_3_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            integrator_3_address0 <= grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_3_address0;
        else 
            integrator_3_address0 <= "XXXXXXX";
        end if; 
    end process;


    integrator_3_ce0_assign_proc : process(grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_3_ce0, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_3_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_3_ce0 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_3_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            integrator_3_ce0 <= grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_3_ce0;
        else 
            integrator_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    integrator_3_ce1_assign_proc : process(grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_3_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_3_ce1 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_3_ce1;
        else 
            integrator_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    integrator_3_d0_assign_proc : process(grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_3_d0, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_3_d0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_3_d0 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_3_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            integrator_3_d0 <= grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_3_d0;
        else 
            integrator_3_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    integrator_3_we0_assign_proc : process(grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_3_we0, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_3_we0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_3_we0 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_3_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            integrator_3_we0 <= grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_3_we0;
        else 
            integrator_3_we0 <= ap_const_logic_0;
        end if; 
    end process;


    integrator_4_address0_assign_proc : process(grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_4_address0, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_4_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_4_address0 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_4_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            integrator_4_address0 <= grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_4_address0;
        else 
            integrator_4_address0 <= "XXXXXXX";
        end if; 
    end process;


    integrator_4_ce0_assign_proc : process(grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_4_ce0, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_4_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_4_ce0 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_4_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            integrator_4_ce0 <= grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_4_ce0;
        else 
            integrator_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    integrator_4_ce1_assign_proc : process(grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_4_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_4_ce1 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_4_ce1;
        else 
            integrator_4_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    integrator_4_d0_assign_proc : process(grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_4_d0, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_4_d0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_4_d0 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_4_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            integrator_4_d0 <= grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_4_d0;
        else 
            integrator_4_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    integrator_4_we0_assign_proc : process(grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_4_we0, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_4_we0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_4_we0 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_4_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            integrator_4_we0 <= grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_4_we0;
        else 
            integrator_4_we0 <= ap_const_logic_0;
        end if; 
    end process;


    integrator_5_address0_assign_proc : process(grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_5_address0, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_5_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_5_address0 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_5_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            integrator_5_address0 <= grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_5_address0;
        else 
            integrator_5_address0 <= "XXXXXXX";
        end if; 
    end process;


    integrator_5_ce0_assign_proc : process(grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_5_ce0, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_5_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_5_ce0 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_5_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            integrator_5_ce0 <= grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_5_ce0;
        else 
            integrator_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    integrator_5_ce1_assign_proc : process(grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_5_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_5_ce1 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_5_ce1;
        else 
            integrator_5_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    integrator_5_d0_assign_proc : process(grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_5_d0, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_5_d0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_5_d0 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_5_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            integrator_5_d0 <= grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_5_d0;
        else 
            integrator_5_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    integrator_5_we0_assign_proc : process(grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_5_we0, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_5_we0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_5_we0 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_5_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            integrator_5_we0 <= grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_5_we0;
        else 
            integrator_5_we0 <= ap_const_logic_0;
        end if; 
    end process;


    integrator_6_address0_assign_proc : process(grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_6_address0, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_6_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_6_address0 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_6_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            integrator_6_address0 <= grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_6_address0;
        else 
            integrator_6_address0 <= "XXXXXXX";
        end if; 
    end process;


    integrator_6_ce0_assign_proc : process(grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_6_ce0, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_6_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_6_ce0 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_6_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            integrator_6_ce0 <= grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_6_ce0;
        else 
            integrator_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    integrator_6_ce1_assign_proc : process(grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_6_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_6_ce1 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_6_ce1;
        else 
            integrator_6_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    integrator_6_d0_assign_proc : process(grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_6_d0, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_6_d0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_6_d0 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_6_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            integrator_6_d0 <= grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_6_d0;
        else 
            integrator_6_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    integrator_6_we0_assign_proc : process(grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_6_we0, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_6_we0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_6_we0 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_6_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            integrator_6_we0 <= grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_6_we0;
        else 
            integrator_6_we0 <= ap_const_logic_0;
        end if; 
    end process;


    integrator_7_address0_assign_proc : process(grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_7_address0, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_7_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_7_address0 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_7_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            integrator_7_address0 <= grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_7_address0;
        else 
            integrator_7_address0 <= "XXXXXXX";
        end if; 
    end process;


    integrator_7_ce0_assign_proc : process(grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_7_ce0, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_7_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_7_ce0 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_7_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            integrator_7_ce0 <= grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_7_ce0;
        else 
            integrator_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    integrator_7_ce1_assign_proc : process(grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_7_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_7_ce1 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_7_ce1;
        else 
            integrator_7_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    integrator_7_d0_assign_proc : process(grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_7_d0, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_7_d0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_7_d0 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_7_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            integrator_7_d0 <= grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_7_d0;
        else 
            integrator_7_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    integrator_7_we0_assign_proc : process(grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_7_we0, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_7_we0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_7_we0 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_7_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            integrator_7_we0 <= grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_7_we0;
        else 
            integrator_7_we0 <= ap_const_logic_0;
        end if; 
    end process;


    integrator_address0_assign_proc : process(grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_address0, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_address0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_address0 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            integrator_address0 <= grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_address0;
        else 
            integrator_address0 <= "XXXXXXX";
        end if; 
    end process;


    integrator_ce0_assign_proc : process(grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_ce0, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_ce0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_ce0 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            integrator_ce0 <= grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_ce0;
        else 
            integrator_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    integrator_ce1_assign_proc : process(grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_ce1, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_ce1 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_ce1;
        else 
            integrator_ce1 <= ap_const_logic_0;
        end if; 
    end process;


    integrator_d0_assign_proc : process(grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_d0, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_d0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_d0 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            integrator_d0 <= grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_d0;
        else 
            integrator_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    integrator_we0_assign_proc : process(grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_we0, grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_we0, ap_CS_fsm_state2, ap_CS_fsm_state4)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
            integrator_we0 <= grp_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP_fu_152_integrator_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            integrator_we0 <= grp_delta_encoding_Pipeline_INIT_LOOP_fu_132_integrator_we0;
        else 
            integrator_we0 <= ap_const_logic_0;
        end if; 
    end process;

    sub1_fu_212_p1 <= sub1_neg_fu_204_p3;
    sub1_neg_fu_204_p3 <= (xor_val_fu_198_p2 & empty_fu_180_p1);
    sub1_to_int_fu_176_p1 <= threshold;
    xor_val_fu_198_p2 <= (bit_sel_fu_190_p3 xor ap_const_lv1_1);
end behav;
