// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module delta_encoding_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RFIFONUM,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        threshold,
        sub1_to_int,
        empty,
        spikes,
        integrator_address0,
        integrator_ce0,
        integrator_we0,
        integrator_d0,
        integrator_address1,
        integrator_ce1,
        integrator_q1,
        integrator_1_address0,
        integrator_1_ce0,
        integrator_1_we0,
        integrator_1_d0,
        integrator_1_address1,
        integrator_1_ce1,
        integrator_1_q1,
        integrator_2_address0,
        integrator_2_ce0,
        integrator_2_we0,
        integrator_2_d0,
        integrator_2_address1,
        integrator_2_ce1,
        integrator_2_q1,
        integrator_3_address0,
        integrator_3_ce0,
        integrator_3_we0,
        integrator_3_d0,
        integrator_3_address1,
        integrator_3_ce1,
        integrator_3_q1,
        integrator_4_address0,
        integrator_4_ce0,
        integrator_4_we0,
        integrator_4_d0,
        integrator_4_address1,
        integrator_4_ce1,
        integrator_4_q1,
        integrator_5_address0,
        integrator_5_ce0,
        integrator_5_we0,
        integrator_5_d0,
        integrator_5_address1,
        integrator_5_ce1,
        integrator_5_q1,
        integrator_6_address0,
        integrator_6_ce0,
        integrator_6_we0,
        integrator_6_d0,
        integrator_6_address1,
        integrator_6_ce1,
        integrator_6_q1,
        integrator_7_address0,
        integrator_7_ce0,
        integrator_7_we0,
        integrator_7_d0,
        integrator_7_address1,
        integrator_7_ce1,
        integrator_7_q1,
        leak,
        p_cast_cast,
        sub1
);

parameter    ap_ST_fsm_pp0_stage0 = 3'd1;
parameter    ap_ST_fsm_pp0_stage1 = 3'd2;
parameter    ap_ST_fsm_pp0_stage2 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [63:0] m_axi_gmem_AWADDR;
output  [0:0] m_axi_gmem_AWID;
output  [31:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [0:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [31:0] m_axi_gmem_WDATA;
output  [3:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [0:0] m_axi_gmem_WID;
output  [0:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [63:0] m_axi_gmem_ARADDR;
output  [0:0] m_axi_gmem_ARID;
output  [31:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [0:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [31:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [0:0] m_axi_gmem_RID;
input  [8:0] m_axi_gmem_RFIFONUM;
input  [0:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [0:0] m_axi_gmem_BID;
input  [0:0] m_axi_gmem_BUSER;
input  [31:0] threshold;
input  [30:0] sub1_to_int;
input  [22:0] empty;
input  [63:0] spikes;
output  [6:0] integrator_address0;
output   integrator_ce0;
output   integrator_we0;
output  [31:0] integrator_d0;
output  [6:0] integrator_address1;
output   integrator_ce1;
input  [31:0] integrator_q1;
output  [6:0] integrator_1_address0;
output   integrator_1_ce0;
output   integrator_1_we0;
output  [31:0] integrator_1_d0;
output  [6:0] integrator_1_address1;
output   integrator_1_ce1;
input  [31:0] integrator_1_q1;
output  [6:0] integrator_2_address0;
output   integrator_2_ce0;
output   integrator_2_we0;
output  [31:0] integrator_2_d0;
output  [6:0] integrator_2_address1;
output   integrator_2_ce1;
input  [31:0] integrator_2_q1;
output  [6:0] integrator_3_address0;
output   integrator_3_ce0;
output   integrator_3_we0;
output  [31:0] integrator_3_d0;
output  [6:0] integrator_3_address1;
output   integrator_3_ce1;
input  [31:0] integrator_3_q1;
output  [6:0] integrator_4_address0;
output   integrator_4_ce0;
output   integrator_4_we0;
output  [31:0] integrator_4_d0;
output  [6:0] integrator_4_address1;
output   integrator_4_ce1;
input  [31:0] integrator_4_q1;
output  [6:0] integrator_5_address0;
output   integrator_5_ce0;
output   integrator_5_we0;
output  [31:0] integrator_5_d0;
output  [6:0] integrator_5_address1;
output   integrator_5_ce1;
input  [31:0] integrator_5_q1;
output  [6:0] integrator_6_address0;
output   integrator_6_ce0;
output   integrator_6_we0;
output  [31:0] integrator_6_d0;
output  [6:0] integrator_6_address1;
output   integrator_6_ce1;
input  [31:0] integrator_6_q1;
output  [6:0] integrator_7_address0;
output   integrator_7_ce0;
output   integrator_7_we0;
output  [31:0] integrator_7_d0;
output  [6:0] integrator_7_address1;
output   integrator_7_ce1;
input  [31:0] integrator_7_q1;
input  [31:0] leak;
input  [61:0] p_cast_cast;
input  [31:0] sub1;

reg ap_idle;
reg m_axi_gmem_AWVALID;
reg[63:0] m_axi_gmem_AWADDR;
reg m_axi_gmem_WVALID;
reg[31:0] m_axi_gmem_WDATA;
reg[3:0] m_axi_gmem_WSTRB;
reg m_axi_gmem_ARVALID;
reg m_axi_gmem_RREADY;
reg m_axi_gmem_BREADY;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage2;
reg   [0:0] and_ln144_1_reg_988;
reg    ap_block_state18_io;
reg   [0:0] and_ln144_1_reg_988_pp0_iter7_reg;
reg    ap_block_state24_pp0_stage2_iter7;
reg    ap_block_pp0_stage2_subdone;
reg   [0:0] icmp_ln136_reg_842;
reg    ap_condition_exit_pp0_iter0_stage2;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_blk_n_AW;
wire    ap_block_pp0_stage2;
reg    gmem_blk_n_W;
wire    ap_block_pp0_stage0;
reg    gmem_blk_n_B;
reg    gmem_blk_n_R;
reg    gmem_blk_n_AR;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1;
reg   [0:0] first_iter_0_reg_858;
wire   [31:0] grp_fu_403_p2;
reg   [31:0] reg_429;
reg    ap_block_state10_pp0_stage0_iter3;
reg    ap_block_state19_io;
reg    ap_block_state25_pp0_stage0_iter8;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] and_ln144_1_reg_988_pp0_iter6_reg;
reg   [0:0] and_ln148_reg_1012;
reg   [0:0] and_ln148_reg_1012_pp0_iter6_reg;
wire  signed [63:0] p_cast_cast_cast_fu_441_p1;
reg  signed [63:0] p_cast_cast_cast_reg_837;
wire   [0:0] icmp_ln136_fu_463_p2;
reg   [0:0] icmp_ln136_reg_842_pp0_iter1_reg;
reg   [0:0] icmp_ln136_reg_842_pp0_iter2_reg;
reg   [0:0] icmp_ln136_reg_842_pp0_iter3_reg;
reg   [0:0] icmp_ln136_reg_842_pp0_iter4_reg;
reg   [0:0] icmp_ln136_reg_842_pp0_iter5_reg;
reg   [0:0] icmp_ln136_reg_842_pp0_iter6_reg;
wire   [0:0] icmp_ln137_fu_478_p2;
reg   [0:0] icmp_ln137_reg_846;
reg   [0:0] icmp_ln137_reg_846_pp0_iter1_reg;
reg   [0:0] icmp_ln137_reg_846_pp0_iter2_reg;
reg   [0:0] icmp_ln137_reg_846_pp0_iter3_reg;
reg   [0:0] icmp_ln137_reg_846_pp0_iter4_reg;
wire   [9:0] select_ln136_fu_484_p3;
reg   [9:0] select_ln136_reg_851;
reg   [9:0] select_ln136_reg_851_pp0_iter1_reg;
reg   [9:0] select_ln136_reg_851_pp0_iter2_reg;
reg   [9:0] select_ln136_reg_851_pp0_iter3_reg;
reg   [9:0] select_ln136_reg_851_pp0_iter4_reg;
wire   [0:0] first_iter_0_fu_492_p2;
wire   [2:0] trunc_ln137_fu_498_p1;
reg   [2:0] trunc_ln137_reg_862;
reg   [2:0] trunc_ln137_reg_862_pp0_iter1_reg;
reg   [2:0] trunc_ln137_reg_862_pp0_iter2_reg;
reg   [2:0] trunc_ln137_reg_862_pp0_iter3_reg;
reg   [2:0] trunc_ln137_reg_862_pp0_iter4_reg;
reg   [2:0] trunc_ln137_reg_862_pp0_iter5_reg;
reg   [2:0] trunc_ln137_reg_862_pp0_iter6_reg;
reg   [2:0] trunc_ln137_reg_862_pp0_iter7_reg;
reg    ap_predicate_op66_readreq_state2;
reg    ap_block_state2_io;
reg    ap_block_state20_io;
reg    ap_block_pp0_stage1_11001;
wire   [0:0] icmp_ln144_2_fu_522_p2;
reg   [0:0] icmp_ln144_2_reg_873;
reg   [0:0] icmp_ln144_2_reg_873_pp0_iter1_reg;
reg   [0:0] icmp_ln144_2_reg_873_pp0_iter2_reg;
reg   [0:0] icmp_ln144_2_reg_873_pp0_iter3_reg;
reg   [0:0] icmp_ln144_2_reg_873_pp0_iter4_reg;
wire   [0:0] icmp_ln144_3_fu_528_p2;
reg   [0:0] icmp_ln144_3_reg_878;
reg   [0:0] icmp_ln144_3_reg_878_pp0_iter1_reg;
reg   [0:0] icmp_ln144_3_reg_878_pp0_iter2_reg;
reg   [0:0] icmp_ln144_3_reg_878_pp0_iter3_reg;
reg   [0:0] icmp_ln144_3_reg_878_pp0_iter4_reg;
reg   [6:0] integrator_addr_reg_883;
reg   [6:0] integrator_addr_reg_883_pp0_iter2_reg;
reg   [6:0] integrator_addr_reg_883_pp0_iter3_reg;
reg   [6:0] integrator_addr_reg_883_pp0_iter4_reg;
reg   [6:0] integrator_addr_reg_883_pp0_iter5_reg;
reg   [6:0] integrator_addr_reg_883_pp0_iter6_reg;
reg   [6:0] integrator_addr_reg_883_pp0_iter7_reg;
reg   [6:0] integrator_1_addr_reg_889;
reg   [6:0] integrator_1_addr_reg_889_pp0_iter2_reg;
reg   [6:0] integrator_1_addr_reg_889_pp0_iter3_reg;
reg   [6:0] integrator_1_addr_reg_889_pp0_iter4_reg;
reg   [6:0] integrator_1_addr_reg_889_pp0_iter5_reg;
reg   [6:0] integrator_1_addr_reg_889_pp0_iter6_reg;
reg   [6:0] integrator_1_addr_reg_889_pp0_iter7_reg;
reg   [6:0] integrator_2_addr_reg_895;
reg   [6:0] integrator_2_addr_reg_895_pp0_iter2_reg;
reg   [6:0] integrator_2_addr_reg_895_pp0_iter3_reg;
reg   [6:0] integrator_2_addr_reg_895_pp0_iter4_reg;
reg   [6:0] integrator_2_addr_reg_895_pp0_iter5_reg;
reg   [6:0] integrator_2_addr_reg_895_pp0_iter6_reg;
reg   [6:0] integrator_2_addr_reg_895_pp0_iter7_reg;
reg   [6:0] integrator_3_addr_reg_901;
reg   [6:0] integrator_3_addr_reg_901_pp0_iter2_reg;
reg   [6:0] integrator_3_addr_reg_901_pp0_iter3_reg;
reg   [6:0] integrator_3_addr_reg_901_pp0_iter4_reg;
reg   [6:0] integrator_3_addr_reg_901_pp0_iter5_reg;
reg   [6:0] integrator_3_addr_reg_901_pp0_iter6_reg;
reg   [6:0] integrator_3_addr_reg_901_pp0_iter7_reg;
reg   [6:0] integrator_4_addr_reg_907;
reg   [6:0] integrator_4_addr_reg_907_pp0_iter2_reg;
reg   [6:0] integrator_4_addr_reg_907_pp0_iter3_reg;
reg   [6:0] integrator_4_addr_reg_907_pp0_iter4_reg;
reg   [6:0] integrator_4_addr_reg_907_pp0_iter5_reg;
reg   [6:0] integrator_4_addr_reg_907_pp0_iter6_reg;
reg   [6:0] integrator_4_addr_reg_907_pp0_iter7_reg;
reg   [6:0] integrator_5_addr_reg_913;
reg   [6:0] integrator_5_addr_reg_913_pp0_iter2_reg;
reg   [6:0] integrator_5_addr_reg_913_pp0_iter3_reg;
reg   [6:0] integrator_5_addr_reg_913_pp0_iter4_reg;
reg   [6:0] integrator_5_addr_reg_913_pp0_iter5_reg;
reg   [6:0] integrator_5_addr_reg_913_pp0_iter6_reg;
reg   [6:0] integrator_5_addr_reg_913_pp0_iter7_reg;
reg   [6:0] integrator_6_addr_reg_919;
reg   [6:0] integrator_6_addr_reg_919_pp0_iter2_reg;
reg   [6:0] integrator_6_addr_reg_919_pp0_iter3_reg;
reg   [6:0] integrator_6_addr_reg_919_pp0_iter4_reg;
reg   [6:0] integrator_6_addr_reg_919_pp0_iter5_reg;
reg   [6:0] integrator_6_addr_reg_919_pp0_iter6_reg;
reg   [6:0] integrator_6_addr_reg_919_pp0_iter7_reg;
reg   [6:0] integrator_7_addr_reg_925;
reg   [6:0] integrator_7_addr_reg_925_pp0_iter2_reg;
reg   [6:0] integrator_7_addr_reg_925_pp0_iter3_reg;
reg   [6:0] integrator_7_addr_reg_925_pp0_iter4_reg;
reg   [6:0] integrator_7_addr_reg_925_pp0_iter5_reg;
reg   [6:0] integrator_7_addr_reg_925_pp0_iter6_reg;
reg   [6:0] integrator_7_addr_reg_925_pp0_iter7_reg;
wire   [31:0] tmp_fu_564_p19;
reg   [31:0] tmp_reg_931;
wire   [31:0] grp_fu_407_p2;
reg   [31:0] mul_reg_936;
reg    ap_block_pp0_stage2_11001;
reg   [31:0] gmem_addr_read_reg_941;
wire   [31:0] bitcast_ln141_fu_603_p1;
wire   [4:0] select_ln136_1_fu_616_p3;
reg   [4:0] select_ln136_1_reg_951;
wire   [14:0] empty_27_fu_631_p2;
reg   [14:0] empty_27_reg_956;
reg   [31:0] add_reg_961;
wire   [63:0] add_ln141_fu_648_p2;
reg   [63:0] add_ln141_reg_976;
wire   [0:0] and_ln144_fu_693_p2;
reg   [0:0] and_ln144_reg_983;
wire   [0:0] grp_fu_415_p2;
wire   [1:0] empty_29_fu_699_p1;
reg   [1:0] empty_29_reg_992;
wire   [3:0] empty_30_fu_706_p2;
reg   [3:0] empty_30_reg_997;
wire   [3:0] shl_ln145_fu_719_p2;
reg   [3:0] shl_ln145_reg_1002;
wire   [24:0] shl_ln145_2_fu_737_p2;
reg   [24:0] shl_ln145_2_reg_1007;
reg   [63:0] gmem_addr_2_reg_1016;
wire   [31:0] empty_31_fu_775_p2;
reg   [31:0] empty_31_reg_1028;
reg    ap_enable_reg_pp0_iter0_reg;
reg    ap_block_pp0_stage0_subdone;
reg   [31:0] ap_phi_mux_storereflowmerge_phi_fu_395_p4;
wire   [31:0] ap_phi_reg_pp0_iter6_storereflowmerge_reg_392;
wire   [63:0] zext_ln137_2_fu_552_p1;
wire  signed [63:0] p_cast2_cast_fu_743_p1;
wire  signed [63:0] sext_ln145_fu_753_p1;
wire   [31:0] zext_ln145_2_fu_781_p1;
reg    ap_block_pp0_stage0_01001;
wire    ap_block_pp0_stage1_01001;
reg   [9:0] i_fu_160;
wire   [9:0] add_ln137_fu_533_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_i_load;
reg   [4:0] t_fu_164;
reg   [14:0] indvar_flatten_fu_168;
wire   [14:0] add_ln136_fu_469_p2;
reg   [14:0] ap_sig_allocacmp_indvar_flatten_load;
reg    integrator_ce1_local;
reg    integrator_we0_local;
reg   [31:0] integrator_d0_local;
reg    integrator_ce0_local;
reg   [6:0] integrator_address0_local;
reg    ap_predicate_pred672_state23;
reg    integrator_1_ce1_local;
reg    integrator_1_we0_local;
reg   [31:0] integrator_1_d0_local;
reg    integrator_1_ce0_local;
reg   [6:0] integrator_1_address0_local;
reg    ap_predicate_pred699_state23;
reg    integrator_2_ce1_local;
reg    integrator_2_we0_local;
reg   [31:0] integrator_2_d0_local;
reg    integrator_2_ce0_local;
reg   [6:0] integrator_2_address0_local;
reg    ap_predicate_pred725_state23;
reg    integrator_3_ce1_local;
reg    integrator_3_we0_local;
reg   [31:0] integrator_3_d0_local;
reg    integrator_3_ce0_local;
reg   [6:0] integrator_3_address0_local;
reg    ap_predicate_pred751_state23;
reg    integrator_4_ce1_local;
reg    integrator_4_we0_local;
reg   [31:0] integrator_4_d0_local;
reg    integrator_4_ce0_local;
reg   [6:0] integrator_4_address0_local;
reg    ap_predicate_pred777_state23;
reg    integrator_5_ce1_local;
reg    integrator_5_we0_local;
reg   [31:0] integrator_5_d0_local;
reg    integrator_5_ce0_local;
reg   [6:0] integrator_5_address0_local;
reg    ap_predicate_pred803_state23;
reg    integrator_6_ce1_local;
reg    integrator_6_we0_local;
reg   [31:0] integrator_6_d0_local;
reg    integrator_6_ce0_local;
reg   [6:0] integrator_6_address0_local;
reg    ap_predicate_pred829_state23;
reg    integrator_7_ce1_local;
reg    integrator_7_we0_local;
reg   [31:0] integrator_7_d0_local;
reg    integrator_7_ce0_local;
reg   [6:0] integrator_7_address0_local;
reg    ap_predicate_pred855_state23;
reg   [31:0] grp_fu_403_p0;
reg   [31:0] grp_fu_403_p1;
reg   [31:0] grp_fu_411_p1;
wire   [0:0] grp_fu_411_p2;
wire   [7:0] tmp_2_fu_513_p4;
wire   [6:0] lshr_ln1_fu_543_p4;
wire   [31:0] tmp_fu_564_p17;
wire   [4:0] add_ln136_1_fu_610_p2;
wire   [4:0] empty_27_fu_631_p0;
wire   [10:0] empty_27_fu_631_p1;
wire   [63:0] zext_ln137_1_fu_640_p1;
wire   [63:0] add_ln141_1_fu_643_p2;
wire   [63:0] zext_ln137_fu_637_p1;
wire   [31:0] bitcast_ln144_fu_654_p1;
wire   [7:0] tmp_1_fu_657_p4;
wire   [22:0] trunc_ln144_fu_667_p1;
wire   [0:0] icmp_ln144_1_fu_677_p2;
wire   [0:0] icmp_ln144_fu_671_p2;
wire   [0:0] or_ln144_fu_683_p2;
wire   [0:0] or_ln144_1_fu_689_p2;
wire   [3:0] add_ln141_cast_cast6_fu_702_p1;
wire   [1:0] trunc_ln145_fu_712_p1;
wire   [3:0] zext_ln145_fu_715_p1;
wire   [4:0] shl_ln145_1_fu_725_p3;
wire   [24:0] zext_ln145_1_fu_733_p1;
wire   [61:0] grp_fu_420_p4;
wire   [4:0] tmp_9_fu_764_p3;
wire   [31:0] p_cast7_fu_771_p1;
reg   [1:0] grp_fu_403_opcode;
wire    ap_block_pp0_stage1_00001;
reg    ap_block_pp0_stage2_00001;
reg    grp_fu_403_ce;
reg    grp_fu_407_ce;
reg    grp_fu_411_ce;
reg    ap_predicate_op152_fcmp_state17;
reg   [4:0] grp_fu_411_opcode;
reg    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter7_stage0;
reg    ap_idle_pp0_0to6;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0_1to8;
reg    ap_block_pp0_stage1_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [14:0] empty_27_fu_631_p00;
reg    ap_condition_1201;
reg    ap_condition_1207;
reg    ap_condition_1211;
wire   [2:0] tmp_fu_564_p1;
wire   [2:0] tmp_fu_564_p3;
wire   [2:0] tmp_fu_564_p5;
wire   [2:0] tmp_fu_564_p7;
wire  signed [2:0] tmp_fu_564_p9;
wire  signed [2:0] tmp_fu_564_p11;
wire  signed [2:0] tmp_fu_564_p13;
wire  signed [2:0] tmp_fu_564_p15;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 i_fu_160 = 10'd0;
#0 t_fu_164 = 5'd0;
#0 indvar_flatten_fu_168 = 15'd0;
#0 ap_done_reg = 1'b0;
end

delta_encoding_faddfsub_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
faddfsub_32ns_32ns_32_5_full_dsp_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_403_p0),
    .din1(grp_fu_403_p1),
    .opcode(grp_fu_403_opcode),
    .ce(grp_fu_403_ce),
    .dout(grp_fu_403_p2)
);

delta_encoding_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(tmp_reg_931),
    .din1(leak),
    .ce(grp_fu_407_ce),
    .dout(grp_fu_407_p2)
);

delta_encoding_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_reg_961),
    .din1(grp_fu_411_p1),
    .ce(grp_fu_411_ce),
    .opcode(grp_fu_411_opcode),
    .dout(grp_fu_411_p2)
);

(* dissolve_hierarchy = "yes" *) delta_encoding_sparsemux_17_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h0 ),
    .din0_WIDTH( 32 ),
    .CASE1( 3'h1 ),
    .din1_WIDTH( 32 ),
    .CASE2( 3'h2 ),
    .din2_WIDTH( 32 ),
    .CASE3( 3'h3 ),
    .din3_WIDTH( 32 ),
    .CASE4( 3'h4 ),
    .din4_WIDTH( 32 ),
    .CASE5( 3'h5 ),
    .din5_WIDTH( 32 ),
    .CASE6( 3'h6 ),
    .din6_WIDTH( 32 ),
    .CASE7( 3'h7 ),
    .din7_WIDTH( 32 ),
    .def_WIDTH( 32 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
sparsemux_17_3_32_1_1_U12(
    .din0(integrator_q1),
    .din1(integrator_1_q1),
    .din2(integrator_2_q1),
    .din3(integrator_3_q1),
    .din4(integrator_4_q1),
    .din5(integrator_5_q1),
    .din6(integrator_6_q1),
    .din7(integrator_7_q1),
    .def(tmp_fu_564_p17),
    .sel(trunc_ln137_reg_862_pp0_iter1_reg),
    .dout(tmp_fu_564_p19)
);

delta_encoding_mul_5ns_11ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 15 ))
mul_5ns_11ns_15_1_1_U13(
    .din0(empty_27_fu_631_p0),
    .din1(empty_27_fu_631_p1),
    .dout(empty_27_fu_631_p2)
);

delta_encoding_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage2),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage2)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter8 <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter7_stage0) & (ap_idle_pp0_0to6 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter7_stage0) & (ap_idle_pp0_0to6 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter7_stage0) & (ap_idle_pp0_0to6 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter7_stage0) & (ap_idle_pp0_0to6 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter7_stage0) & (ap_idle_pp0_0to6 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter7_stage0) & (ap_idle_pp0_0to6 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_condition_exit_pp0_iter7_stage0) & (ap_idle_pp0_0to6 == 1'b1))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= 1'b0;
    end else if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        i_fu_160 <= 10'd0;
    end else if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln136_reg_842 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        i_fu_160 <= add_ln137_fu_533_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        if (((icmp_ln136_fu_463_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_168 <= add_ln136_fu_469_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_168 <= 15'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        t_fu_164 <= 5'd0;
    end else if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        t_fu_164 <= select_ln136_1_fu_616_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        add_ln141_reg_976 <= add_ln141_fu_648_p2;
        and_ln144_reg_983 <= and_ln144_fu_693_p2;
        ap_predicate_pred672_state23 <= ((trunc_ln137_reg_862_pp0_iter6_reg == 3'd0) & (1'd0 == and_ln144_1_reg_988_pp0_iter6_reg) & (1'd1 == and_ln148_reg_1012_pp0_iter6_reg));
        ap_predicate_pred699_state23 <= ((trunc_ln137_reg_862_pp0_iter6_reg == 3'd1) & (1'd0 == and_ln144_1_reg_988_pp0_iter6_reg) & (1'd1 == and_ln148_reg_1012_pp0_iter6_reg));
        ap_predicate_pred725_state23 <= ((trunc_ln137_reg_862_pp0_iter6_reg == 3'd2) & (1'd0 == and_ln144_1_reg_988_pp0_iter6_reg) & (1'd1 == and_ln148_reg_1012_pp0_iter6_reg));
        ap_predicate_pred751_state23 <= ((trunc_ln137_reg_862_pp0_iter6_reg == 3'd3) & (1'd0 == and_ln144_1_reg_988_pp0_iter6_reg) & (1'd1 == and_ln148_reg_1012_pp0_iter6_reg));
        ap_predicate_pred777_state23 <= ((trunc_ln137_reg_862_pp0_iter6_reg == 3'd4) & (1'd0 == and_ln144_1_reg_988_pp0_iter6_reg) & (1'd1 == and_ln148_reg_1012_pp0_iter6_reg));
        ap_predicate_pred803_state23 <= ((trunc_ln137_reg_862_pp0_iter6_reg == 3'd5) & (1'd0 == and_ln144_1_reg_988_pp0_iter6_reg) & (1'd1 == and_ln148_reg_1012_pp0_iter6_reg));
        ap_predicate_pred829_state23 <= ((trunc_ln137_reg_862_pp0_iter6_reg == 3'd6) & (1'd0 == and_ln144_1_reg_988_pp0_iter6_reg) & (1'd1 == and_ln148_reg_1012_pp0_iter6_reg));
        ap_predicate_pred855_state23 <= ((trunc_ln137_reg_862_pp0_iter6_reg == 3'd7) & (1'd0 == and_ln144_1_reg_988_pp0_iter6_reg) & (1'd1 == and_ln148_reg_1012_pp0_iter6_reg));
        empty_31_reg_1028 <= empty_31_fu_775_p2;
        first_iter_0_reg_858 <= first_iter_0_fu_492_p2;
        gmem_addr_read_reg_941 <= m_axi_gmem_RDATA;
        icmp_ln136_reg_842 <= icmp_ln136_fu_463_p2;
        icmp_ln136_reg_842_pp0_iter1_reg <= icmp_ln136_reg_842;
        icmp_ln136_reg_842_pp0_iter2_reg <= icmp_ln136_reg_842_pp0_iter1_reg;
        icmp_ln136_reg_842_pp0_iter3_reg <= icmp_ln136_reg_842_pp0_iter2_reg;
        icmp_ln136_reg_842_pp0_iter4_reg <= icmp_ln136_reg_842_pp0_iter3_reg;
        icmp_ln136_reg_842_pp0_iter5_reg <= icmp_ln136_reg_842_pp0_iter4_reg;
        icmp_ln136_reg_842_pp0_iter6_reg <= icmp_ln136_reg_842_pp0_iter5_reg;
        icmp_ln137_reg_846 <= icmp_ln137_fu_478_p2;
        icmp_ln137_reg_846_pp0_iter1_reg <= icmp_ln137_reg_846;
        icmp_ln137_reg_846_pp0_iter2_reg <= icmp_ln137_reg_846_pp0_iter1_reg;
        icmp_ln137_reg_846_pp0_iter3_reg <= icmp_ln137_reg_846_pp0_iter2_reg;
        icmp_ln137_reg_846_pp0_iter4_reg <= icmp_ln137_reg_846_pp0_iter3_reg;
        integrator_1_addr_reg_889 <= zext_ln137_2_fu_552_p1;
        integrator_1_addr_reg_889_pp0_iter2_reg <= integrator_1_addr_reg_889;
        integrator_1_addr_reg_889_pp0_iter3_reg <= integrator_1_addr_reg_889_pp0_iter2_reg;
        integrator_1_addr_reg_889_pp0_iter4_reg <= integrator_1_addr_reg_889_pp0_iter3_reg;
        integrator_1_addr_reg_889_pp0_iter5_reg <= integrator_1_addr_reg_889_pp0_iter4_reg;
        integrator_1_addr_reg_889_pp0_iter6_reg <= integrator_1_addr_reg_889_pp0_iter5_reg;
        integrator_1_addr_reg_889_pp0_iter7_reg <= integrator_1_addr_reg_889_pp0_iter6_reg;
        integrator_2_addr_reg_895 <= zext_ln137_2_fu_552_p1;
        integrator_2_addr_reg_895_pp0_iter2_reg <= integrator_2_addr_reg_895;
        integrator_2_addr_reg_895_pp0_iter3_reg <= integrator_2_addr_reg_895_pp0_iter2_reg;
        integrator_2_addr_reg_895_pp0_iter4_reg <= integrator_2_addr_reg_895_pp0_iter3_reg;
        integrator_2_addr_reg_895_pp0_iter5_reg <= integrator_2_addr_reg_895_pp0_iter4_reg;
        integrator_2_addr_reg_895_pp0_iter6_reg <= integrator_2_addr_reg_895_pp0_iter5_reg;
        integrator_2_addr_reg_895_pp0_iter7_reg <= integrator_2_addr_reg_895_pp0_iter6_reg;
        integrator_3_addr_reg_901 <= zext_ln137_2_fu_552_p1;
        integrator_3_addr_reg_901_pp0_iter2_reg <= integrator_3_addr_reg_901;
        integrator_3_addr_reg_901_pp0_iter3_reg <= integrator_3_addr_reg_901_pp0_iter2_reg;
        integrator_3_addr_reg_901_pp0_iter4_reg <= integrator_3_addr_reg_901_pp0_iter3_reg;
        integrator_3_addr_reg_901_pp0_iter5_reg <= integrator_3_addr_reg_901_pp0_iter4_reg;
        integrator_3_addr_reg_901_pp0_iter6_reg <= integrator_3_addr_reg_901_pp0_iter5_reg;
        integrator_3_addr_reg_901_pp0_iter7_reg <= integrator_3_addr_reg_901_pp0_iter6_reg;
        integrator_4_addr_reg_907 <= zext_ln137_2_fu_552_p1;
        integrator_4_addr_reg_907_pp0_iter2_reg <= integrator_4_addr_reg_907;
        integrator_4_addr_reg_907_pp0_iter3_reg <= integrator_4_addr_reg_907_pp0_iter2_reg;
        integrator_4_addr_reg_907_pp0_iter4_reg <= integrator_4_addr_reg_907_pp0_iter3_reg;
        integrator_4_addr_reg_907_pp0_iter5_reg <= integrator_4_addr_reg_907_pp0_iter4_reg;
        integrator_4_addr_reg_907_pp0_iter6_reg <= integrator_4_addr_reg_907_pp0_iter5_reg;
        integrator_4_addr_reg_907_pp0_iter7_reg <= integrator_4_addr_reg_907_pp0_iter6_reg;
        integrator_5_addr_reg_913 <= zext_ln137_2_fu_552_p1;
        integrator_5_addr_reg_913_pp0_iter2_reg <= integrator_5_addr_reg_913;
        integrator_5_addr_reg_913_pp0_iter3_reg <= integrator_5_addr_reg_913_pp0_iter2_reg;
        integrator_5_addr_reg_913_pp0_iter4_reg <= integrator_5_addr_reg_913_pp0_iter3_reg;
        integrator_5_addr_reg_913_pp0_iter5_reg <= integrator_5_addr_reg_913_pp0_iter4_reg;
        integrator_5_addr_reg_913_pp0_iter6_reg <= integrator_5_addr_reg_913_pp0_iter5_reg;
        integrator_5_addr_reg_913_pp0_iter7_reg <= integrator_5_addr_reg_913_pp0_iter6_reg;
        integrator_6_addr_reg_919 <= zext_ln137_2_fu_552_p1;
        integrator_6_addr_reg_919_pp0_iter2_reg <= integrator_6_addr_reg_919;
        integrator_6_addr_reg_919_pp0_iter3_reg <= integrator_6_addr_reg_919_pp0_iter2_reg;
        integrator_6_addr_reg_919_pp0_iter4_reg <= integrator_6_addr_reg_919_pp0_iter3_reg;
        integrator_6_addr_reg_919_pp0_iter5_reg <= integrator_6_addr_reg_919_pp0_iter4_reg;
        integrator_6_addr_reg_919_pp0_iter6_reg <= integrator_6_addr_reg_919_pp0_iter5_reg;
        integrator_6_addr_reg_919_pp0_iter7_reg <= integrator_6_addr_reg_919_pp0_iter6_reg;
        integrator_7_addr_reg_925 <= zext_ln137_2_fu_552_p1;
        integrator_7_addr_reg_925_pp0_iter2_reg <= integrator_7_addr_reg_925;
        integrator_7_addr_reg_925_pp0_iter3_reg <= integrator_7_addr_reg_925_pp0_iter2_reg;
        integrator_7_addr_reg_925_pp0_iter4_reg <= integrator_7_addr_reg_925_pp0_iter3_reg;
        integrator_7_addr_reg_925_pp0_iter5_reg <= integrator_7_addr_reg_925_pp0_iter4_reg;
        integrator_7_addr_reg_925_pp0_iter6_reg <= integrator_7_addr_reg_925_pp0_iter5_reg;
        integrator_7_addr_reg_925_pp0_iter7_reg <= integrator_7_addr_reg_925_pp0_iter6_reg;
        integrator_addr_reg_883 <= zext_ln137_2_fu_552_p1;
        integrator_addr_reg_883_pp0_iter2_reg <= integrator_addr_reg_883;
        integrator_addr_reg_883_pp0_iter3_reg <= integrator_addr_reg_883_pp0_iter2_reg;
        integrator_addr_reg_883_pp0_iter4_reg <= integrator_addr_reg_883_pp0_iter3_reg;
        integrator_addr_reg_883_pp0_iter5_reg <= integrator_addr_reg_883_pp0_iter4_reg;
        integrator_addr_reg_883_pp0_iter6_reg <= integrator_addr_reg_883_pp0_iter5_reg;
        integrator_addr_reg_883_pp0_iter7_reg <= integrator_addr_reg_883_pp0_iter6_reg;
        p_cast_cast_cast_reg_837 <= p_cast_cast_cast_fu_441_p1;
        select_ln136_reg_851 <= select_ln136_fu_484_p3;
        select_ln136_reg_851_pp0_iter1_reg <= select_ln136_reg_851;
        select_ln136_reg_851_pp0_iter2_reg <= select_ln136_reg_851_pp0_iter1_reg;
        select_ln136_reg_851_pp0_iter3_reg <= select_ln136_reg_851_pp0_iter2_reg;
        select_ln136_reg_851_pp0_iter4_reg <= select_ln136_reg_851_pp0_iter3_reg;
        trunc_ln137_reg_862 <= trunc_ln137_fu_498_p1;
        trunc_ln137_reg_862_pp0_iter1_reg <= trunc_ln137_reg_862;
        trunc_ln137_reg_862_pp0_iter2_reg <= trunc_ln137_reg_862_pp0_iter1_reg;
        trunc_ln137_reg_862_pp0_iter3_reg <= trunc_ln137_reg_862_pp0_iter2_reg;
        trunc_ln137_reg_862_pp0_iter4_reg <= trunc_ln137_reg_862_pp0_iter3_reg;
        trunc_ln137_reg_862_pp0_iter5_reg <= trunc_ln137_reg_862_pp0_iter4_reg;
        trunc_ln137_reg_862_pp0_iter6_reg <= trunc_ln137_reg_862_pp0_iter5_reg;
        trunc_ln137_reg_862_pp0_iter7_reg <= trunc_ln137_reg_862_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        add_reg_961 <= grp_fu_403_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        and_ln144_1_reg_988 <= grp_fu_415_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        and_ln144_1_reg_988_pp0_iter6_reg <= and_ln144_1_reg_988;
        and_ln144_1_reg_988_pp0_iter7_reg <= and_ln144_1_reg_988_pp0_iter6_reg;
        empty_29_reg_992 <= empty_29_fu_699_p1;
        empty_30_reg_997 <= empty_30_fu_706_p2;
        icmp_ln144_2_reg_873 <= icmp_ln144_2_fu_522_p2;
        icmp_ln144_2_reg_873_pp0_iter1_reg <= icmp_ln144_2_reg_873;
        icmp_ln144_2_reg_873_pp0_iter2_reg <= icmp_ln144_2_reg_873_pp0_iter1_reg;
        icmp_ln144_2_reg_873_pp0_iter3_reg <= icmp_ln144_2_reg_873_pp0_iter2_reg;
        icmp_ln144_2_reg_873_pp0_iter4_reg <= icmp_ln144_2_reg_873_pp0_iter3_reg;
        icmp_ln144_3_reg_878 <= icmp_ln144_3_fu_528_p2;
        icmp_ln144_3_reg_878_pp0_iter1_reg <= icmp_ln144_3_reg_878;
        icmp_ln144_3_reg_878_pp0_iter2_reg <= icmp_ln144_3_reg_878_pp0_iter1_reg;
        icmp_ln144_3_reg_878_pp0_iter3_reg <= icmp_ln144_3_reg_878_pp0_iter2_reg;
        icmp_ln144_3_reg_878_pp0_iter4_reg <= icmp_ln144_3_reg_878_pp0_iter3_reg;
        select_ln136_1_reg_951 <= select_ln136_1_fu_616_p3;
        shl_ln145_2_reg_1007 <= shl_ln145_2_fu_737_p2;
        shl_ln145_reg_1002 <= shl_ln145_fu_719_p2;
        tmp_reg_931 <= tmp_fu_564_p19;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        and_ln148_reg_1012 <= grp_fu_415_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001))) begin
        and_ln148_reg_1012_pp0_iter6_reg <= and_ln148_reg_1012;
        empty_27_reg_956 <= empty_27_fu_631_p2;
        gmem_addr_2_reg_1016 <= p_cast2_cast_fu_743_p1;
        mul_reg_936 <= grp_fu_407_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln144_1_reg_988_pp0_iter6_reg)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd0 == and_ln144_1_reg_988_pp0_iter6_reg) & (1'd1 == and_ln148_reg_1012_pp0_iter6_reg)))) begin
        reg_429 <= grp_fu_403_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (icmp_ln136_reg_842 == 1'd1) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b1) & (icmp_ln136_reg_842_pp0_iter6_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter7_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter7_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter7_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to6 = 1'b1;
    end else begin
        ap_idle_pp0_0to6 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to8 = 1'b1;
    end else begin
        ap_idle_pp0_1to8 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln136_reg_842_pp0_iter5_reg == 1'd0) & (1'd0 == and_ln144_1_reg_988))) begin
        if ((1'd0 == and_ln148_reg_1012)) begin
            ap_phi_mux_storereflowmerge_phi_fu_395_p4 = 32'd0;
        end else if ((1'd1 == and_ln148_reg_1012)) begin
            ap_phi_mux_storereflowmerge_phi_fu_395_p4 = 32'd255;
        end else begin
            ap_phi_mux_storereflowmerge_phi_fu_395_p4 = ap_phi_reg_pp0_iter6_storereflowmerge_reg_392;
        end
    end else begin
        ap_phi_mux_storereflowmerge_phi_fu_395_p4 = ap_phi_reg_pp0_iter6_storereflowmerge_reg_392;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_i_load = 10'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_160;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 15'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_168;
    end
end

always @ (*) begin
    if (((first_iter_0_reg_858 == 1'd1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (icmp_ln136_reg_842 == 1'd0) & (1'b0 == ap_block_pp0_stage1))) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (1'd0 == and_ln144_1_reg_988)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2) & (1'd1 == and_ln144_1_reg_988)))) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (1'd0 == and_ln144_1_reg_988_pp0_iter7_reg)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2) & (1'd1 == and_ln144_1_reg_988_pp0_iter7_reg)))) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem_blk_n_R = m_axi_gmem_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (1'd0 == and_ln144_1_reg_988)) | ((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (1'd1 == and_ln144_1_reg_988)))) begin
        gmem_blk_n_W = m_axi_gmem_WREADY;
    end else begin
        gmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_403_ce = 1'b1;
    end else begin
        grp_fu_403_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_00001) & (1'd1 == and_ln144_1_reg_988))) begin
        grp_fu_403_opcode = 2'd1;
    end else if ((((grp_fu_415_p2 == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_00001) & (1'd0 == and_ln144_1_reg_988)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_00001)))) begin
        grp_fu_403_opcode = 2'd0;
    end else begin
        grp_fu_403_opcode = 'bx;
    end
end

always @ (*) begin
    if ((((grp_fu_415_p2 == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2) & (1'd0 == and_ln144_1_reg_988)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2) & (1'd1 == and_ln144_1_reg_988)))) begin
        grp_fu_403_p0 = add_reg_961;
    end else if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        grp_fu_403_p0 = mul_reg_936;
    end else begin
        grp_fu_403_p0 = 'bx;
    end
end

always @ (*) begin
    if ((((grp_fu_415_p2 == 1'd1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2) & (1'd0 == and_ln144_1_reg_988)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2) & (1'd1 == and_ln144_1_reg_988)))) begin
        grp_fu_403_p1 = threshold;
    end else if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
        grp_fu_403_p1 = bitcast_ln141_fu_603_p1;
    end else begin
        grp_fu_403_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_407_ce = 1'b1;
    end else begin
        grp_fu_407_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        grp_fu_411_ce = 1'b1;
    end else begin
        grp_fu_411_ce = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
        if ((1'b1 == ap_condition_1201)) begin
            grp_fu_411_opcode = 5'd4;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_00001))) begin
            grp_fu_411_opcode = 5'd2;
        end else begin
            grp_fu_411_opcode = 'bx;
        end
    end else begin
        grp_fu_411_opcode = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter5 == 1'b1)) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1))) begin
            grp_fu_411_p1 = sub1;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
            grp_fu_411_p1 = threshold;
        end else begin
            grp_fu_411_p1 = 'bx;
        end
    end else begin
        grp_fu_411_p1 = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred699_state23 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln137_reg_862_pp0_iter7_reg == 3'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (1'd1 == and_ln144_1_reg_988_pp0_iter6_reg)))) begin
        integrator_1_address0_local = integrator_1_addr_reg_889_pp0_iter7_reg;
    end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        integrator_1_address0_local = integrator_1_addr_reg_889_pp0_iter4_reg;
    end else begin
        integrator_1_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred699_state23 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln137_reg_862_pp0_iter7_reg == 3'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'd1 == and_ln144_1_reg_988_pp0_iter6_reg)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        integrator_1_ce0_local = 1'b1;
    end else begin
        integrator_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        integrator_1_ce1_local = 1'b1;
    end else begin
        integrator_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred699_state23 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln137_reg_862_pp0_iter7_reg == 3'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (1'd1 == and_ln144_1_reg_988_pp0_iter6_reg)))) begin
        integrator_1_d0_local = reg_429;
    end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        integrator_1_d0_local = add_reg_961;
    end else begin
        integrator_1_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred699_state23 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((trunc_ln137_reg_862_pp0_iter4_reg == 3'd1) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln137_reg_862_pp0_iter7_reg == 3'd1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'd1 == and_ln144_1_reg_988_pp0_iter6_reg)))) begin
        integrator_1_we0_local = 1'b1;
    end else begin
        integrator_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred725_state23 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln137_reg_862_pp0_iter7_reg == 3'd2) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (1'd1 == and_ln144_1_reg_988_pp0_iter6_reg)))) begin
        integrator_2_address0_local = integrator_2_addr_reg_895_pp0_iter7_reg;
    end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        integrator_2_address0_local = integrator_2_addr_reg_895_pp0_iter4_reg;
    end else begin
        integrator_2_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred725_state23 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln137_reg_862_pp0_iter7_reg == 3'd2) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'd1 == and_ln144_1_reg_988_pp0_iter6_reg)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        integrator_2_ce0_local = 1'b1;
    end else begin
        integrator_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        integrator_2_ce1_local = 1'b1;
    end else begin
        integrator_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred725_state23 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln137_reg_862_pp0_iter7_reg == 3'd2) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (1'd1 == and_ln144_1_reg_988_pp0_iter6_reg)))) begin
        integrator_2_d0_local = reg_429;
    end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        integrator_2_d0_local = add_reg_961;
    end else begin
        integrator_2_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred725_state23 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((trunc_ln137_reg_862_pp0_iter4_reg == 3'd2) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln137_reg_862_pp0_iter7_reg == 3'd2) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'd1 == and_ln144_1_reg_988_pp0_iter6_reg)))) begin
        integrator_2_we0_local = 1'b1;
    end else begin
        integrator_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred751_state23 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln137_reg_862_pp0_iter7_reg == 3'd3) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (1'd1 == and_ln144_1_reg_988_pp0_iter6_reg)))) begin
        integrator_3_address0_local = integrator_3_addr_reg_901_pp0_iter7_reg;
    end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        integrator_3_address0_local = integrator_3_addr_reg_901_pp0_iter4_reg;
    end else begin
        integrator_3_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred751_state23 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln137_reg_862_pp0_iter7_reg == 3'd3) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'd1 == and_ln144_1_reg_988_pp0_iter6_reg)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        integrator_3_ce0_local = 1'b1;
    end else begin
        integrator_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        integrator_3_ce1_local = 1'b1;
    end else begin
        integrator_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred751_state23 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln137_reg_862_pp0_iter7_reg == 3'd3) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (1'd1 == and_ln144_1_reg_988_pp0_iter6_reg)))) begin
        integrator_3_d0_local = reg_429;
    end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        integrator_3_d0_local = add_reg_961;
    end else begin
        integrator_3_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred751_state23 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((trunc_ln137_reg_862_pp0_iter4_reg == 3'd3) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln137_reg_862_pp0_iter7_reg == 3'd3) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'd1 == and_ln144_1_reg_988_pp0_iter6_reg)))) begin
        integrator_3_we0_local = 1'b1;
    end else begin
        integrator_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred777_state23 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln137_reg_862_pp0_iter7_reg == 3'd4) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (1'd1 == and_ln144_1_reg_988_pp0_iter6_reg)))) begin
        integrator_4_address0_local = integrator_4_addr_reg_907_pp0_iter7_reg;
    end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        integrator_4_address0_local = integrator_4_addr_reg_907_pp0_iter4_reg;
    end else begin
        integrator_4_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred777_state23 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln137_reg_862_pp0_iter7_reg == 3'd4) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'd1 == and_ln144_1_reg_988_pp0_iter6_reg)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        integrator_4_ce0_local = 1'b1;
    end else begin
        integrator_4_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        integrator_4_ce1_local = 1'b1;
    end else begin
        integrator_4_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred777_state23 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln137_reg_862_pp0_iter7_reg == 3'd4) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (1'd1 == and_ln144_1_reg_988_pp0_iter6_reg)))) begin
        integrator_4_d0_local = reg_429;
    end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        integrator_4_d0_local = add_reg_961;
    end else begin
        integrator_4_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred777_state23 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((trunc_ln137_reg_862_pp0_iter4_reg == 3'd4) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln137_reg_862_pp0_iter7_reg == 3'd4) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'd1 == and_ln144_1_reg_988_pp0_iter6_reg)))) begin
        integrator_4_we0_local = 1'b1;
    end else begin
        integrator_4_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred803_state23 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln137_reg_862_pp0_iter7_reg == 3'd5) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (1'd1 == and_ln144_1_reg_988_pp0_iter6_reg)))) begin
        integrator_5_address0_local = integrator_5_addr_reg_913_pp0_iter7_reg;
    end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        integrator_5_address0_local = integrator_5_addr_reg_913_pp0_iter4_reg;
    end else begin
        integrator_5_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred803_state23 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln137_reg_862_pp0_iter7_reg == 3'd5) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'd1 == and_ln144_1_reg_988_pp0_iter6_reg)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        integrator_5_ce0_local = 1'b1;
    end else begin
        integrator_5_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        integrator_5_ce1_local = 1'b1;
    end else begin
        integrator_5_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred803_state23 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln137_reg_862_pp0_iter7_reg == 3'd5) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (1'd1 == and_ln144_1_reg_988_pp0_iter6_reg)))) begin
        integrator_5_d0_local = reg_429;
    end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        integrator_5_d0_local = add_reg_961;
    end else begin
        integrator_5_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred803_state23 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((trunc_ln137_reg_862_pp0_iter4_reg == 3'd5) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln137_reg_862_pp0_iter7_reg == 3'd5) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'd1 == and_ln144_1_reg_988_pp0_iter6_reg)))) begin
        integrator_5_we0_local = 1'b1;
    end else begin
        integrator_5_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred829_state23 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln137_reg_862_pp0_iter7_reg == 3'd6) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (1'd1 == and_ln144_1_reg_988_pp0_iter6_reg)))) begin
        integrator_6_address0_local = integrator_6_addr_reg_919_pp0_iter7_reg;
    end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        integrator_6_address0_local = integrator_6_addr_reg_919_pp0_iter4_reg;
    end else begin
        integrator_6_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred829_state23 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln137_reg_862_pp0_iter7_reg == 3'd6) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'd1 == and_ln144_1_reg_988_pp0_iter6_reg)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        integrator_6_ce0_local = 1'b1;
    end else begin
        integrator_6_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        integrator_6_ce1_local = 1'b1;
    end else begin
        integrator_6_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred829_state23 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln137_reg_862_pp0_iter7_reg == 3'd6) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (1'd1 == and_ln144_1_reg_988_pp0_iter6_reg)))) begin
        integrator_6_d0_local = reg_429;
    end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        integrator_6_d0_local = add_reg_961;
    end else begin
        integrator_6_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred829_state23 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((trunc_ln137_reg_862_pp0_iter4_reg == 3'd6) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln137_reg_862_pp0_iter7_reg == 3'd6) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'd1 == and_ln144_1_reg_988_pp0_iter6_reg)))) begin
        integrator_6_we0_local = 1'b1;
    end else begin
        integrator_6_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred855_state23 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln137_reg_862_pp0_iter7_reg == 3'd7) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (1'd1 == and_ln144_1_reg_988_pp0_iter6_reg)))) begin
        integrator_7_address0_local = integrator_7_addr_reg_925_pp0_iter7_reg;
    end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        integrator_7_address0_local = integrator_7_addr_reg_925_pp0_iter4_reg;
    end else begin
        integrator_7_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred855_state23 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln137_reg_862_pp0_iter7_reg == 3'd7) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'd1 == and_ln144_1_reg_988_pp0_iter6_reg)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        integrator_7_ce0_local = 1'b1;
    end else begin
        integrator_7_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        integrator_7_ce1_local = 1'b1;
    end else begin
        integrator_7_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred855_state23 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln137_reg_862_pp0_iter7_reg == 3'd7) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (1'd1 == and_ln144_1_reg_988_pp0_iter6_reg)))) begin
        integrator_7_d0_local = reg_429;
    end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        integrator_7_d0_local = add_reg_961;
    end else begin
        integrator_7_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred855_state23 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((trunc_ln137_reg_862_pp0_iter4_reg == 3'd7) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln137_reg_862_pp0_iter7_reg == 3'd7) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'd1 == and_ln144_1_reg_988_pp0_iter6_reg)))) begin
        integrator_7_we0_local = 1'b1;
    end else begin
        integrator_7_we0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred672_state23 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln137_reg_862_pp0_iter7_reg == 3'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (1'd1 == and_ln144_1_reg_988_pp0_iter6_reg)))) begin
        integrator_address0_local = integrator_addr_reg_883_pp0_iter7_reg;
    end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        integrator_address0_local = integrator_addr_reg_883_pp0_iter4_reg;
    end else begin
        integrator_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred672_state23 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln137_reg_862_pp0_iter7_reg == 3'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'd1 == and_ln144_1_reg_988_pp0_iter6_reg)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        integrator_ce0_local = 1'b1;
    end else begin
        integrator_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        integrator_ce1_local = 1'b1;
    end else begin
        integrator_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred672_state23 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln137_reg_862_pp0_iter7_reg == 3'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1) & (1'd1 == and_ln144_1_reg_988_pp0_iter6_reg)))) begin
        integrator_d0_local = reg_429;
    end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        integrator_d0_local = add_reg_961;
    end else begin
        integrator_d0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_predicate_pred672_state23 == 1'b1) & (ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001)) | ((trunc_ln137_reg_862_pp0_iter4_reg == 3'd0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (trunc_ln137_reg_862_pp0_iter7_reg == 3'd0) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'd1 == and_ln144_1_reg_988_pp0_iter6_reg)))) begin
        integrator_we0_local = 1'b1;
    end else begin
        integrator_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op66_readreq_state2 == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001))) begin
        m_axi_gmem_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd0 == and_ln144_1_reg_988))) begin
        m_axi_gmem_AWADDR = gmem_addr_2_reg_1016;
    end else if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001) & (1'd1 == and_ln144_1_reg_988))) begin
        m_axi_gmem_AWADDR = sext_ln145_fu_753_p1;
    end else begin
        m_axi_gmem_AWADDR = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd0 == and_ln144_1_reg_988)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001) & (1'd1 == and_ln144_1_reg_988)))) begin
        m_axi_gmem_AWVALID = 1'b1;
    end else begin
        m_axi_gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd0 == and_ln144_1_reg_988_pp0_iter7_reg)) | ((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2) & (1'b0 == ap_block_pp0_stage2_11001) & (1'd1 == and_ln144_1_reg_988_pp0_iter7_reg)))) begin
        m_axi_gmem_BREADY = 1'b1;
    end else begin
        m_axi_gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        m_axi_gmem_RREADY = 1'b1;
    end else begin
        m_axi_gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter6 == 1'b1)) begin
        if ((1'b1 == ap_condition_1211)) begin
            m_axi_gmem_WDATA = empty_31_reg_1028;
        end else if ((1'b1 == ap_condition_1207)) begin
            m_axi_gmem_WDATA = zext_ln145_2_fu_781_p1;
        end else begin
            m_axi_gmem_WDATA = 'bx;
        end
    end else begin
        m_axi_gmem_WDATA = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter6 == 1'b1)) begin
        if ((1'b1 == ap_condition_1211)) begin
            m_axi_gmem_WSTRB = empty_30_reg_997;
        end else if ((1'b1 == ap_condition_1207)) begin
            m_axi_gmem_WSTRB = shl_ln145_reg_1002;
        end else begin
            m_axi_gmem_WSTRB = 'bx;
        end
    end else begin
        m_axi_gmem_WSTRB = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'd0 == and_ln144_1_reg_988)) | ((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln144_1_reg_988)))) begin
        m_axi_gmem_WVALID = 1'b1;
    end else begin
        m_axi_gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((1'b1 == ap_condition_exit_pp0_iter7_stage0) & (ap_idle_pp0_0to6 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to8 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln136_1_fu_610_p2 = (t_fu_164 + 5'd1);

assign add_ln136_fu_469_p2 = (ap_sig_allocacmp_indvar_flatten_load + 15'd1);

assign add_ln137_fu_533_p2 = (select_ln136_reg_851 + 10'd1);

assign add_ln141_1_fu_643_p2 = (zext_ln137_1_fu_640_p1 + spikes);

assign add_ln141_cast_cast6_fu_702_p1 = empty_29_fu_699_p1;

assign add_ln141_fu_648_p2 = (add_ln141_1_fu_643_p2 + zext_ln137_fu_637_p1);

assign and_ln144_fu_693_p2 = (or_ln144_fu_683_p2 & or_ln144_1_fu_689_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_00001 = (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_block_state25_pp0_stage0_iter8)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage0_iter3)));
end

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_block_state25_pp0_stage0_iter8)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage0_iter3)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_block_state25_pp0_stage0_iter8)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state19_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter8 == 1'b1) & (1'b1 == ap_block_state25_pp0_stage0_iter8)) | ((ap_enable_reg_pp0_iter3 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage0_iter3)) | ((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state19_io)));
end

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_01001 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state20_io)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_io)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((ap_enable_reg_pp0_iter6 == 1'b1) & (1'b1 == ap_block_state20_io)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_io)));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage2_00001 = ((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_block_state24_pp0_stage2_iter7));
end

always @ (*) begin
    ap_block_pp0_stage2_11001 = (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_block_state24_pp0_stage2_iter7)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state18_io)));
end

always @ (*) begin
    ap_block_pp0_stage2_subdone = (((ap_enable_reg_pp0_iter7 == 1'b1) & (1'b1 == ap_block_state24_pp0_stage2_iter7)) | ((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b1 == ap_block_state18_io)));
end

always @ (*) begin
    ap_block_state10_pp0_stage0_iter3 = (m_axi_gmem_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state18_io = ((m_axi_gmem_AWREADY == 1'b0) & (1'd1 == and_ln144_1_reg_988));
end

always @ (*) begin
    ap_block_state19_io = (((m_axi_gmem_WREADY == 1'b0) & (1'd1 == and_ln144_1_reg_988)) | ((m_axi_gmem_AWREADY == 1'b0) & (1'd0 == and_ln144_1_reg_988)));
end

always @ (*) begin
    ap_block_state20_io = ((m_axi_gmem_WREADY == 1'b0) & (1'd0 == and_ln144_1_reg_988));
end

always @ (*) begin
    ap_block_state24_pp0_stage2_iter7 = ((1'd1 == and_ln144_1_reg_988_pp0_iter7_reg) & (m_axi_gmem_BVALID == 1'b0));
end

always @ (*) begin
    ap_block_state25_pp0_stage0_iter8 = ((1'd0 == and_ln144_1_reg_988_pp0_iter7_reg) & (m_axi_gmem_BVALID == 1'b0));
end

always @ (*) begin
    ap_block_state2_io = ((m_axi_gmem_ARREADY == 1'b0) & (ap_predicate_op66_readreq_state2 == 1'b1));
end

always @ (*) begin
    ap_condition_1201 = ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_00001) & (ap_predicate_op152_fcmp_state17 == 1'b1));
end

always @ (*) begin
    ap_condition_1207 = ((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_01001) & (1'd1 == and_ln144_1_reg_988));
end

always @ (*) begin
    ap_condition_1211 = ((1'b1 == ap_CS_fsm_pp0_stage1) & (1'b0 == ap_block_pp0_stage1_01001) & (1'd0 == and_ln144_1_reg_988));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage2;

assign ap_phi_reg_pp0_iter6_storereflowmerge_reg_392 = 'bx;

always @ (*) begin
    ap_predicate_op152_fcmp_state17 = ((grp_fu_415_p2 == 1'd0) & (icmp_ln136_reg_842_pp0_iter5_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op66_readreq_state2 = ((first_iter_0_reg_858 == 1'd1) & (icmp_ln136_reg_842 == 1'd0));
end

assign ap_ready = ap_ready_sig;

assign bitcast_ln141_fu_603_p1 = gmem_addr_read_reg_941;

assign bitcast_ln144_fu_654_p1 = add_reg_961;

assign empty_27_fu_631_p0 = empty_27_fu_631_p00;

assign empty_27_fu_631_p00 = select_ln136_1_reg_951;

assign empty_27_fu_631_p1 = 15'd784;

assign empty_29_fu_699_p1 = add_ln141_reg_976[1:0];

assign empty_30_fu_706_p2 = 4'd1 << add_ln141_cast_cast6_fu_702_p1;

assign empty_31_fu_775_p2 = ap_phi_mux_storereflowmerge_phi_fu_395_p4 << p_cast7_fu_771_p1;

assign first_iter_0_fu_492_p2 = ((select_ln136_fu_484_p3 == 10'd0) ? 1'b1 : 1'b0);

assign grp_fu_415_p2 = (grp_fu_411_p2 & and_ln144_reg_983);

assign grp_fu_420_p4 = {{add_ln141_reg_976[63:2]}};

assign icmp_ln136_fu_463_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 15'd19600) ? 1'b1 : 1'b0);

assign icmp_ln137_fu_478_p2 = ((ap_sig_allocacmp_i_load == 10'd784) ? 1'b1 : 1'b0);

assign icmp_ln144_1_fu_677_p2 = ((trunc_ln144_fu_667_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln144_2_fu_522_p2 = ((tmp_2_fu_513_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln144_3_fu_528_p2 = ((empty == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln144_fu_671_p2 = ((tmp_1_fu_657_p4 != 8'd255) ? 1'b1 : 1'b0);

assign integrator_1_address0 = integrator_1_address0_local;

assign integrator_1_address1 = zext_ln137_2_fu_552_p1;

assign integrator_1_ce0 = integrator_1_ce0_local;

assign integrator_1_ce1 = integrator_1_ce1_local;

assign integrator_1_d0 = integrator_1_d0_local;

assign integrator_1_we0 = integrator_1_we0_local;

assign integrator_2_address0 = integrator_2_address0_local;

assign integrator_2_address1 = zext_ln137_2_fu_552_p1;

assign integrator_2_ce0 = integrator_2_ce0_local;

assign integrator_2_ce1 = integrator_2_ce1_local;

assign integrator_2_d0 = integrator_2_d0_local;

assign integrator_2_we0 = integrator_2_we0_local;

assign integrator_3_address0 = integrator_3_address0_local;

assign integrator_3_address1 = zext_ln137_2_fu_552_p1;

assign integrator_3_ce0 = integrator_3_ce0_local;

assign integrator_3_ce1 = integrator_3_ce1_local;

assign integrator_3_d0 = integrator_3_d0_local;

assign integrator_3_we0 = integrator_3_we0_local;

assign integrator_4_address0 = integrator_4_address0_local;

assign integrator_4_address1 = zext_ln137_2_fu_552_p1;

assign integrator_4_ce0 = integrator_4_ce0_local;

assign integrator_4_ce1 = integrator_4_ce1_local;

assign integrator_4_d0 = integrator_4_d0_local;

assign integrator_4_we0 = integrator_4_we0_local;

assign integrator_5_address0 = integrator_5_address0_local;

assign integrator_5_address1 = zext_ln137_2_fu_552_p1;

assign integrator_5_ce0 = integrator_5_ce0_local;

assign integrator_5_ce1 = integrator_5_ce1_local;

assign integrator_5_d0 = integrator_5_d0_local;

assign integrator_5_we0 = integrator_5_we0_local;

assign integrator_6_address0 = integrator_6_address0_local;

assign integrator_6_address1 = zext_ln137_2_fu_552_p1;

assign integrator_6_ce0 = integrator_6_ce0_local;

assign integrator_6_ce1 = integrator_6_ce1_local;

assign integrator_6_d0 = integrator_6_d0_local;

assign integrator_6_we0 = integrator_6_we0_local;

assign integrator_7_address0 = integrator_7_address0_local;

assign integrator_7_address1 = zext_ln137_2_fu_552_p1;

assign integrator_7_ce0 = integrator_7_ce0_local;

assign integrator_7_ce1 = integrator_7_ce1_local;

assign integrator_7_d0 = integrator_7_d0_local;

assign integrator_7_we0 = integrator_7_we0_local;

assign integrator_address0 = integrator_address0_local;

assign integrator_address1 = zext_ln137_2_fu_552_p1;

assign integrator_ce0 = integrator_ce0_local;

assign integrator_ce1 = integrator_ce1_local;

assign integrator_d0 = integrator_d0_local;

assign integrator_we0 = integrator_we0_local;

assign lshr_ln1_fu_543_p4 = {{select_ln136_reg_851[9:3]}};

assign m_axi_gmem_ARADDR = p_cast_cast_cast_reg_837;

assign m_axi_gmem_ARBURST = 2'd0;

assign m_axi_gmem_ARCACHE = 4'd0;

assign m_axi_gmem_ARID = 1'd0;

assign m_axi_gmem_ARLEN = 64'd784;

assign m_axi_gmem_ARLOCK = 2'd0;

assign m_axi_gmem_ARPROT = 3'd0;

assign m_axi_gmem_ARQOS = 4'd0;

assign m_axi_gmem_ARREGION = 4'd0;

assign m_axi_gmem_ARSIZE = 3'd0;

assign m_axi_gmem_ARUSER = 1'd0;

assign m_axi_gmem_AWBURST = 2'd0;

assign m_axi_gmem_AWCACHE = 4'd0;

assign m_axi_gmem_AWID = 1'd0;

assign m_axi_gmem_AWLEN = 64'd1;

assign m_axi_gmem_AWLOCK = 2'd0;

assign m_axi_gmem_AWPROT = 3'd0;

assign m_axi_gmem_AWQOS = 4'd0;

assign m_axi_gmem_AWREGION = 4'd0;

assign m_axi_gmem_AWSIZE = 3'd0;

assign m_axi_gmem_AWUSER = 1'd0;

assign m_axi_gmem_WID = 1'd0;

assign m_axi_gmem_WLAST = 1'b0;

assign m_axi_gmem_WUSER = 1'd0;

assign or_ln144_1_fu_689_p2 = (icmp_ln144_3_reg_878_pp0_iter4_reg | icmp_ln144_2_reg_873_pp0_iter4_reg);

assign or_ln144_fu_683_p2 = (icmp_ln144_fu_671_p2 | icmp_ln144_1_fu_677_p2);

assign p_cast2_cast_fu_743_p1 = $signed(grp_fu_420_p4);

assign p_cast7_fu_771_p1 = tmp_9_fu_764_p3;

assign p_cast_cast_cast_fu_441_p1 = $signed(p_cast_cast);

assign select_ln136_1_fu_616_p3 = ((icmp_ln137_reg_846_pp0_iter4_reg[0:0] == 1'b1) ? add_ln136_1_fu_610_p2 : t_fu_164);

assign select_ln136_fu_484_p3 = ((icmp_ln137_fu_478_p2[0:0] == 1'b1) ? 10'd0 : ap_sig_allocacmp_i_load);

assign sext_ln145_fu_753_p1 = $signed(grp_fu_420_p4);

assign shl_ln145_1_fu_725_p3 = {{trunc_ln145_fu_712_p1}, {3'd0}};

assign shl_ln145_2_fu_737_p2 = 25'd1 << zext_ln145_1_fu_733_p1;

assign shl_ln145_fu_719_p2 = 4'd1 << zext_ln145_fu_715_p1;

assign tmp_1_fu_657_p4 = {{bitcast_ln144_fu_654_p1[30:23]}};

assign tmp_2_fu_513_p4 = {{sub1_to_int[30:23]}};

assign tmp_9_fu_764_p3 = {{empty_29_reg_992}, {3'd0}};

assign tmp_fu_564_p17 = 'bx;

assign trunc_ln137_fu_498_p1 = select_ln136_fu_484_p3[2:0];

assign trunc_ln144_fu_667_p1 = bitcast_ln144_fu_654_p1[22:0];

assign trunc_ln145_fu_712_p1 = add_ln141_reg_976[1:0];

assign zext_ln137_1_fu_640_p1 = select_ln136_reg_851_pp0_iter4_reg;

assign zext_ln137_2_fu_552_p1 = lshr_ln1_fu_543_p4;

assign zext_ln137_fu_637_p1 = empty_27_reg_956;

assign zext_ln145_1_fu_733_p1 = shl_ln145_1_fu_725_p3;

assign zext_ln145_2_fu_781_p1 = shl_ln145_2_reg_1007;

assign zext_ln145_fu_715_p1 = trunc_ln145_fu_712_p1;

endmodule //delta_encoding_delta_encoding_Pipeline_TIME_LOOP_PIXEL_LOOP
