// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="rate_encoding_rate_encoding,hls_ip_2024_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=19620,HLS_SYN_TPT=none,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=2053,HLS_SYN_LUT=2126,HLS_VERSION=2024_1}" *)

module rate_encoding (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        interrupt
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;
parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_enable_reg_pp0_iter14;
reg    ap_enable_reg_pp0_iter15;
reg    ap_enable_reg_pp0_iter16;
reg    ap_enable_reg_pp0_iter17;
reg    ap_enable_reg_pp0_iter18;
reg    ap_enable_reg_pp0_iter19;
reg    ap_idle_pp0;
wire    ap_ready;
reg    gmem_AWVALID;
wire    gmem_AWREADY;
wire   [31:0] gmem_AWLEN;
reg    gmem_WVALID;
wire    gmem_WREADY;
wire   [31:0] gmem_WDATA;
reg    gmem_ARVALID;
wire    gmem_ARREADY;
wire   [31:0] gmem_ARLEN;
wire    gmem_RVALID;
reg    gmem_RREADY;
wire   [31:0] gmem_RDATA;
wire   [8:0] gmem_RFIFONUM;
wire    gmem_BVALID;
reg    gmem_BREADY;
reg   [0:0] first_iter_0_reg_639;
reg    ap_block_state2_io;
reg    ap_block_state10_pp0_stage0_iter9;
reg    ap_block_state20_pp0_stage0_iter19;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln54_fu_376_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg;
reg    ap_block_pp0_stage0_11001;
reg    ap_condition_exit_pp0_iter0_stage0_pp0_iter2_reg;
reg    ap_condition_exit_pp0_iter0_stage0_pp0_iter3_reg;
reg    ap_condition_exit_pp0_iter0_stage0_pp0_iter4_reg;
reg    ap_condition_exit_pp0_iter0_stage0_pp0_iter5_reg;
reg    ap_condition_exit_pp0_iter0_stage0_pp0_iter6_reg;
reg    ap_condition_exit_pp0_iter0_stage0_pp0_iter7_reg;
reg    ap_condition_exit_pp0_iter0_stage0_pp0_iter8_reg;
reg    ap_condition_exit_pp0_iter0_stage0_pp0_iter9_reg;
reg    ap_condition_exit_pp0_iter0_stage0_pp0_iter10_reg;
reg    ap_condition_exit_pp0_iter0_stage0_pp0_iter11_reg;
reg    ap_loop_exit_ready_delayed;
wire   [63:0] img;
wire   [63:0] spikes;
wire   [15:0] seed;
reg    gmem_blk_n_AR;
wire    ap_block_pp0_stage0;
reg    gmem_blk_n_R;
reg    gmem_blk_n_AW;
reg    gmem_blk_n_W;
reg    gmem_blk_n_B;
reg   [0:0] icmp_ln556_reg_199;
reg   [0:0] icmp_ln556_reg_199_pp0_iter1_reg;
reg   [0:0] icmp_ln556_reg_199_pp0_iter2_reg;
reg   [0:0] icmp_ln556_reg_199_pp0_iter3_reg;
reg   [0:0] icmp_ln556_reg_199_pp0_iter4_reg;
reg   [0:0] icmp_ln556_reg_199_pp0_iter5_reg;
reg   [0:0] icmp_ln556_reg_199_pp0_iter6_reg;
reg   [0:0] icmp_ln556_reg_199_pp0_iter7_reg;
reg   [0:0] icmp_ln556_reg_199_pp0_iter8_reg;
reg   [0:0] icmp_ln556_reg_199_pp0_iter9_reg;
reg   [0:0] icmp_ln556_reg_199_pp0_iter10_reg;
reg   [63:0] spikes_read_reg_623;
reg   [63:0] spikes_read_reg_623_pp0_iter1_reg;
reg   [63:0] spikes_read_reg_623_pp0_iter2_reg;
reg   [63:0] spikes_read_reg_623_pp0_iter3_reg;
reg   [63:0] spikes_read_reg_623_pp0_iter4_reg;
reg   [63:0] spikes_read_reg_623_pp0_iter5_reg;
reg   [63:0] spikes_read_reg_623_pp0_iter6_reg;
reg   [63:0] spikes_read_reg_623_pp0_iter7_reg;
reg   [63:0] spikes_read_reg_623_pp0_iter8_reg;
reg   [63:0] spikes_read_reg_623_pp0_iter9_reg;
reg   [63:0] spikes_read_reg_623_pp0_iter10_reg;
reg   [63:0] spikes_read_reg_623_pp0_iter11_reg;
reg   [63:0] gmem_addr_reg_628;
wire   [9:0] select_ln54_fu_277_p3;
reg   [9:0] select_ln54_reg_634;
reg   [9:0] select_ln54_reg_634_pp0_iter1_reg;
reg   [9:0] select_ln54_reg_634_pp0_iter2_reg;
reg   [9:0] select_ln54_reg_634_pp0_iter3_reg;
reg   [9:0] select_ln54_reg_634_pp0_iter4_reg;
reg   [9:0] select_ln54_reg_634_pp0_iter5_reg;
reg   [9:0] select_ln54_reg_634_pp0_iter6_reg;
reg   [9:0] select_ln54_reg_634_pp0_iter7_reg;
reg   [9:0] select_ln54_reg_634_pp0_iter8_reg;
reg   [9:0] select_ln54_reg_634_pp0_iter9_reg;
reg   [9:0] select_ln54_reg_634_pp0_iter10_reg;
reg   [9:0] select_ln54_reg_634_pp0_iter11_reg;
wire   [0:0] first_iter_0_fu_285_p2;
wire   [31:0] or_ln_fu_356_p3;
reg   [31:0] or_ln_reg_643;
wire   [0:0] icmp_ln55_fu_370_p2;
reg   [0:0] icmp_ln55_reg_648;
reg   [0:0] icmp_ln54_reg_653;
wire   [31:0] grp_fu_215_p1;
reg   [31:0] conv_i_reg_657;
reg   [31:0] gmem_addr_read_reg_662;
reg   [31:0] gmem_addr_read_reg_662_pp0_iter10_reg;
reg   [7:0] tmp_1_reg_667;
wire   [22:0] trunc_ln62_2_fu_407_p1;
reg   [22:0] trunc_ln62_2_reg_672;
wire   [31:0] grp_fu_210_p2;
reg   [31:0] rand_val_reg_677;
wire   [0:0] icmp_ln62_2_fu_411_p2;
reg   [0:0] icmp_ln62_2_reg_683;
reg   [0:0] icmp_ln62_2_reg_683_pp0_iter11_reg;
reg   [0:0] icmp_ln62_2_reg_683_pp0_iter12_reg;
wire   [0:0] icmp_ln62_3_fu_416_p2;
reg   [0:0] icmp_ln62_3_reg_688;
reg   [0:0] icmp_ln62_3_reg_688_pp0_iter11_reg;
reg   [0:0] icmp_ln62_3_reg_688_pp0_iter12_reg;
wire   [14:0] mul_ln55_fu_439_p2;
reg   [14:0] mul_ln55_reg_693;
wire   [0:0] icmp_ln62_fu_466_p2;
reg   [0:0] icmp_ln62_reg_703;
reg   [0:0] icmp_ln62_reg_703_pp0_iter12_reg;
wire   [0:0] icmp_ln62_1_fu_472_p2;
reg   [0:0] icmp_ln62_1_reg_708;
reg   [0:0] icmp_ln62_1_reg_708_pp0_iter12_reg;
wire   [0:0] grp_fu_218_p2;
reg   [0:0] tmp_2_reg_713;
wire   [1:0] trunc_ln62_3_fu_511_p1;
reg   [1:0] trunc_ln62_3_reg_718;
reg   [63:0] gmem_addr_1_reg_724;
wire   [3:0] shl_ln62_fu_561_p2;
reg   [3:0] shl_ln62_reg_730;
wire   [24:0] shl_ln62_2_fu_578_p2;
reg   [24:0] shl_ln62_2_reg_735;
reg   [0:0] ap_phi_mux_icmp_ln556_phi_fu_202_p4;
wire    ap_loop_init;
wire  signed [63:0] p_cast_cast_fu_236_p1;
wire  signed [63:0] sext_ln62_fu_525_p1;
reg    ap_block_pp0_stage0_01001;
reg   [14:0] indvar_flatten2_fu_134;
wire   [14:0] add_ln54_1_fu_291_p2;
reg   [14:0] ap_sig_allocacmp_indvar_flatten2_load;
reg   [4:0] t3_fu_138;
wire   [4:0] t_fu_427_p3;
reg   [31:0] or_i74_fu_142;
wire   [31:0] zext_ln52_fu_222_p1;
reg   [31:0] ap_sig_allocacmp_or_i74_load;
reg   [9:0] i5_fu_146;
wire   [9:0] i_fu_364_p2;
reg   [9:0] ap_sig_allocacmp_i5_load;
reg   [4:0] add_ln547_fu_150;
wire   [4:0] add_ln54_fu_478_p2;
wire   [31:0] grp_fu_218_p1;
wire   [61:0] p_cast_fu_226_p4;
wire   [0:0] tmp_4_fu_312_p3;
wire   [0:0] tmp_5_fu_320_p3;
wire   [0:0] xor_ln18_2_fu_338_p2;
wire   [0:0] tmp_3_fu_304_p3;
wire   [0:0] xor_ln18_1_fu_344_p2;
wire   [0:0] trunc_ln17_fu_300_p1;
wire   [0:0] xor_ln18_fu_350_p2;
wire   [30:0] lshr_ln_fu_328_p4;
wire   [4:0] mul_ln55_fu_439_p0;
wire   [10:0] mul_ln55_fu_439_p1;
wire   [31:0] bitcast_ln62_fu_449_p1;
wire   [7:0] tmp_fu_452_p4;
wire   [22:0] trunc_ln62_fu_462_p1;
wire   [63:0] zext_ln55_1_fu_497_p1;
wire   [63:0] add_ln62_1_fu_500_p2;
wire   [63:0] zext_ln55_fu_494_p1;
wire   [63:0] add_ln62_fu_505_p2;
wire   [61:0] trunc_ln62_1_fu_515_p4;
wire   [0:0] or_ln62_fu_535_p2;
wire   [0:0] or_ln62_1_fu_539_p2;
wire   [0:0] and_ln62_fu_543_p2;
wire   [0:0] and_ln62_1_fu_549_p2;
wire   [3:0] zext_ln62_1_fu_558_p1;
wire   [4:0] shl_ln62_1_fu_567_p3;
wire   [24:0] zext_ln62_fu_554_p1;
wire   [24:0] zext_ln62_2_fu_574_p1;
reg    grp_fu_210_ce;
reg    grp_fu_215_ce;
reg    grp_fu_218_ce;
reg    ap_block_pp0_stage0_00001;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg    ap_loop_exit_ready_pp0_iter13_reg;
reg    ap_loop_exit_ready_pp0_iter14_reg;
reg    ap_loop_exit_ready_pp0_iter15_reg;
reg    ap_loop_exit_ready_pp0_iter16_reg;
reg    ap_loop_exit_ready_pp0_iter17_reg;
reg    ap_loop_exit_ready_pp0_iter18_reg;
reg    ap_loop_exit_ready_pp0_iter19_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [14:0] mul_ln55_fu_439_p00;
reg    ap_condition_535;
reg    ap_condition_856;
reg    ap_condition_361;
reg    ap_condition_862;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 ap_enable_reg_pp0_iter14 = 1'b0;
#0 ap_enable_reg_pp0_iter15 = 1'b0;
#0 ap_enable_reg_pp0_iter16 = 1'b0;
#0 ap_enable_reg_pp0_iter17 = 1'b0;
#0 ap_enable_reg_pp0_iter18 = 1'b0;
#0 ap_enable_reg_pp0_iter19 = 1'b0;
#0 indvar_flatten2_fu_134 = 15'd0;
#0 t3_fu_138 = 5'd0;
#0 or_i74_fu_142 = 32'd0;
#0 i5_fu_146 = 10'd0;
#0 add_ln547_fu_150 = 5'd0;
#0 ap_done_reg = 1'b0;
end

rate_encoding_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .img(img),
    .spikes(spikes),
    .seed(seed),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

rate_encoding_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem_ARVALID),
    .I_CH0_ARREADY(gmem_ARREADY),
    .I_CH0_ARADDR(gmem_addr_reg_628),
    .I_CH0_ARLEN(gmem_ARLEN),
    .I_CH0_RVALID(gmem_RVALID),
    .I_CH0_RREADY(gmem_RREADY),
    .I_CH0_RDATA(gmem_RDATA),
    .I_CH0_RFIFONUM(gmem_RFIFONUM),
    .I_CH0_AWVALID(gmem_AWVALID),
    .I_CH0_AWREADY(gmem_AWREADY),
    .I_CH0_AWADDR(gmem_addr_1_reg_724),
    .I_CH0_AWLEN(gmem_AWLEN),
    .I_CH0_WVALID(gmem_WVALID),
    .I_CH0_WREADY(gmem_WREADY),
    .I_CH0_WDATA(gmem_WDATA),
    .I_CH0_WSTRB(shl_ln62_reg_730),
    .I_CH0_BVALID(gmem_BVALID),
    .I_CH0_BREADY(gmem_BREADY)
);

rate_encoding_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(conv_i_reg_657),
    .din1(32'd796917760),
    .ce(grp_fu_210_ce),
    .dout(grp_fu_210_p2)
);

rate_encoding_uitofp_32ns_32_6_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
uitofp_32ns_32_6_no_dsp_1_U2(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(or_ln_reg_643),
    .ce(grp_fu_215_ce),
    .dout(grp_fu_215_p1)
);

rate_encoding_fcmp_32ns_32ns_1_2_no_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_1_U3(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(rand_val_reg_677),
    .din1(grp_fu_218_p1),
    .ce(grp_fu_218_ce),
    .opcode(5'd4),
    .dout(grp_fu_218_p2)
);

rate_encoding_mul_5ns_11ns_15_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 5 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 15 ))
mul_5ns_11ns_15_1_1_U4(
    .din0(mul_ln55_fu_439_p0),
    .din1(mul_ln55_fu_439_p1),
    .dout(mul_ln55_fu_439_p2)
);

rate_encoding_flow_control_loop_delay_pipe flow_control_loop_delay_pipe_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int),
    .ap_continue(1'b1),
    .ap_loop_exit_ready_delayed(ap_loop_exit_ready_delayed)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter19_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter14 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter15 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter16 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter17 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter17 <= ap_enable_reg_pp0_iter16;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter18 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter18 <= ap_enable_reg_pp0_iter17;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter19 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter19 <= ap_enable_reg_pp0_iter18;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if ((1'b1 == ap_condition_535)) begin
            add_ln547_fu_150 <= 5'd1;
        end else if ((ap_enable_reg_pp0_iter11 == 1'b1)) begin
            add_ln547_fu_150 <= add_ln54_fu_478_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_loop_exit_ready_pp0_iter18_reg == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_loop_exit_ready_pp0_iter19_reg <= 1'b0;
    end else if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter19_reg <= ap_loop_exit_ready_pp0_iter18_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_361)) begin
        i5_fu_146 <= i_fu_364_p2;
    end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
    if ((1'b1 == ap_condition_862)) begin
        icmp_ln556_reg_199 <= icmp_ln55_reg_648;
    end else if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        icmp_ln556_reg_199 <= 1'd0;
    end
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_361)) begin
    indvar_flatten2_fu_134 <= add_ln54_1_fu_291_p2;
end
end

always @ (posedge ap_clk) begin
if ((1'b1 == ap_condition_361)) begin
    or_i74_fu_142 <= or_ln_fu_356_p3;
end
end

always @ (posedge ap_clk) begin
if ((1'b0 == ap_block_pp0_stage0_11001)) begin
    if ((1'b1 == ap_condition_535)) begin
        t3_fu_138 <= 5'd0;
    end else if ((ap_enable_reg_pp0_iter11 == 1'b1)) begin
        t3_fu_138 <= t_fu_427_p3;
    end
end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_condition_exit_pp0_iter0_stage0_pp0_iter10_reg <= ap_condition_exit_pp0_iter0_stage0_pp0_iter9_reg;
        ap_condition_exit_pp0_iter0_stage0_pp0_iter11_reg <= ap_condition_exit_pp0_iter0_stage0_pp0_iter10_reg;
        ap_condition_exit_pp0_iter0_stage0_pp0_iter3_reg <= ap_condition_exit_pp0_iter0_stage0_pp0_iter2_reg;
        ap_condition_exit_pp0_iter0_stage0_pp0_iter4_reg <= ap_condition_exit_pp0_iter0_stage0_pp0_iter3_reg;
        ap_condition_exit_pp0_iter0_stage0_pp0_iter5_reg <= ap_condition_exit_pp0_iter0_stage0_pp0_iter4_reg;
        ap_condition_exit_pp0_iter0_stage0_pp0_iter6_reg <= ap_condition_exit_pp0_iter0_stage0_pp0_iter5_reg;
        ap_condition_exit_pp0_iter0_stage0_pp0_iter7_reg <= ap_condition_exit_pp0_iter0_stage0_pp0_iter6_reg;
        ap_condition_exit_pp0_iter0_stage0_pp0_iter8_reg <= ap_condition_exit_pp0_iter0_stage0_pp0_iter7_reg;
        ap_condition_exit_pp0_iter0_stage0_pp0_iter9_reg <= ap_condition_exit_pp0_iter0_stage0_pp0_iter8_reg;
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter13_reg <= ap_loop_exit_ready_pp0_iter12_reg;
        ap_loop_exit_ready_pp0_iter14_reg <= ap_loop_exit_ready_pp0_iter13_reg;
        ap_loop_exit_ready_pp0_iter15_reg <= ap_loop_exit_ready_pp0_iter14_reg;
        ap_loop_exit_ready_pp0_iter16_reg <= ap_loop_exit_ready_pp0_iter15_reg;
        ap_loop_exit_ready_pp0_iter17_reg <= ap_loop_exit_ready_pp0_iter16_reg;
        ap_loop_exit_ready_pp0_iter18_reg <= ap_loop_exit_ready_pp0_iter17_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        conv_i_reg_657 <= grp_fu_215_p1;
        gmem_addr_1_reg_724 <= sext_ln62_fu_525_p1;
        gmem_addr_read_reg_662 <= gmem_RDATA;
        gmem_addr_read_reg_662_pp0_iter10_reg <= gmem_addr_read_reg_662;
        icmp_ln556_reg_199_pp0_iter10_reg <= icmp_ln556_reg_199_pp0_iter9_reg;
        icmp_ln556_reg_199_pp0_iter2_reg <= icmp_ln556_reg_199_pp0_iter1_reg;
        icmp_ln556_reg_199_pp0_iter3_reg <= icmp_ln556_reg_199_pp0_iter2_reg;
        icmp_ln556_reg_199_pp0_iter4_reg <= icmp_ln556_reg_199_pp0_iter3_reg;
        icmp_ln556_reg_199_pp0_iter5_reg <= icmp_ln556_reg_199_pp0_iter4_reg;
        icmp_ln556_reg_199_pp0_iter6_reg <= icmp_ln556_reg_199_pp0_iter5_reg;
        icmp_ln556_reg_199_pp0_iter7_reg <= icmp_ln556_reg_199_pp0_iter6_reg;
        icmp_ln556_reg_199_pp0_iter8_reg <= icmp_ln556_reg_199_pp0_iter7_reg;
        icmp_ln556_reg_199_pp0_iter9_reg <= icmp_ln556_reg_199_pp0_iter8_reg;
        icmp_ln62_1_reg_708 <= icmp_ln62_1_fu_472_p2;
        icmp_ln62_1_reg_708_pp0_iter12_reg <= icmp_ln62_1_reg_708;
        icmp_ln62_2_reg_683 <= icmp_ln62_2_fu_411_p2;
        icmp_ln62_2_reg_683_pp0_iter11_reg <= icmp_ln62_2_reg_683;
        icmp_ln62_2_reg_683_pp0_iter12_reg <= icmp_ln62_2_reg_683_pp0_iter11_reg;
        icmp_ln62_3_reg_688 <= icmp_ln62_3_fu_416_p2;
        icmp_ln62_3_reg_688_pp0_iter11_reg <= icmp_ln62_3_reg_688;
        icmp_ln62_3_reg_688_pp0_iter12_reg <= icmp_ln62_3_reg_688_pp0_iter11_reg;
        icmp_ln62_reg_703 <= icmp_ln62_fu_466_p2;
        icmp_ln62_reg_703_pp0_iter12_reg <= icmp_ln62_reg_703;
        mul_ln55_reg_693 <= mul_ln55_fu_439_p2;
        rand_val_reg_677 <= grp_fu_210_p2;
        select_ln54_reg_634_pp0_iter10_reg <= select_ln54_reg_634_pp0_iter9_reg;
        select_ln54_reg_634_pp0_iter11_reg <= select_ln54_reg_634_pp0_iter10_reg;
        select_ln54_reg_634_pp0_iter2_reg <= select_ln54_reg_634_pp0_iter1_reg;
        select_ln54_reg_634_pp0_iter3_reg <= select_ln54_reg_634_pp0_iter2_reg;
        select_ln54_reg_634_pp0_iter4_reg <= select_ln54_reg_634_pp0_iter3_reg;
        select_ln54_reg_634_pp0_iter5_reg <= select_ln54_reg_634_pp0_iter4_reg;
        select_ln54_reg_634_pp0_iter6_reg <= select_ln54_reg_634_pp0_iter5_reg;
        select_ln54_reg_634_pp0_iter7_reg <= select_ln54_reg_634_pp0_iter6_reg;
        select_ln54_reg_634_pp0_iter8_reg <= select_ln54_reg_634_pp0_iter7_reg;
        select_ln54_reg_634_pp0_iter9_reg <= select_ln54_reg_634_pp0_iter8_reg;
        shl_ln62_2_reg_735 <= shl_ln62_2_fu_578_p2;
        shl_ln62_reg_730 <= shl_ln62_fu_561_p2;
        spikes_read_reg_623_pp0_iter10_reg <= spikes_read_reg_623_pp0_iter9_reg;
        spikes_read_reg_623_pp0_iter11_reg <= spikes_read_reg_623_pp0_iter10_reg;
        spikes_read_reg_623_pp0_iter2_reg <= spikes_read_reg_623_pp0_iter1_reg;
        spikes_read_reg_623_pp0_iter3_reg <= spikes_read_reg_623_pp0_iter2_reg;
        spikes_read_reg_623_pp0_iter4_reg <= spikes_read_reg_623_pp0_iter3_reg;
        spikes_read_reg_623_pp0_iter5_reg <= spikes_read_reg_623_pp0_iter4_reg;
        spikes_read_reg_623_pp0_iter6_reg <= spikes_read_reg_623_pp0_iter5_reg;
        spikes_read_reg_623_pp0_iter7_reg <= spikes_read_reg_623_pp0_iter6_reg;
        spikes_read_reg_623_pp0_iter8_reg <= spikes_read_reg_623_pp0_iter7_reg;
        spikes_read_reg_623_pp0_iter9_reg <= spikes_read_reg_623_pp0_iter8_reg;
        tmp_1_reg_667 <= {{gmem_RDATA[30:23]}};
        tmp_2_reg_713 <= grp_fu_218_p2;
        trunc_ln62_2_reg_672 <= trunc_ln62_2_fu_407_p1;
        trunc_ln62_3_reg_718 <= trunc_ln62_3_fu_511_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg <= ap_condition_exit_pp0_iter0_stage0;
        ap_condition_exit_pp0_iter0_stage0_pp0_iter2_reg <= ap_condition_exit_pp0_iter0_stage0_pp0_iter1_reg;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        first_iter_0_reg_639 <= first_iter_0_fu_285_p2;
        gmem_addr_reg_628 <= p_cast_cast_fu_236_p1;
        icmp_ln54_reg_653 <= icmp_ln54_fu_376_p2;
        icmp_ln556_reg_199_pp0_iter1_reg <= icmp_ln556_reg_199;
        or_ln_reg_643 <= or_ln_fu_356_p3;
        select_ln54_reg_634 <= select_ln54_fu_277_p3;
        select_ln54_reg_634_pp0_iter1_reg <= select_ln54_reg_634;
        spikes_read_reg_623 <= spikes;
        spikes_read_reg_623_pp0_iter1_reg <= spikes_read_reg_623;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        icmp_ln55_reg_648 <= icmp_ln55_fu_370_p2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln54_fu_376_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter19_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b0) & (ap_enable_reg_pp0_iter18 == 1'b0) & (ap_enable_reg_pp0_iter17 == 1'b0) & (ap_enable_reg_pp0_iter16 == 1'b0) & (ap_enable_reg_pp0_iter15 == 1'b0) & (ap_enable_reg_pp0_iter14 == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_condition_exit_pp0_iter0_stage0_pp0_iter11_reg) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_loop_exit_ready_delayed = 1'b1;
    end else begin
        ap_loop_exit_ready_delayed = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        if ((1'b1 == ap_condition_856)) begin
            ap_phi_mux_icmp_ln556_phi_fu_202_p4 = icmp_ln55_reg_648;
        end else if ((ap_loop_init == 1'b1)) begin
            ap_phi_mux_icmp_ln556_phi_fu_202_p4 = 1'd0;
        end else begin
            ap_phi_mux_icmp_ln556_phi_fu_202_p4 = icmp_ln55_reg_648;
        end
    end else begin
        ap_phi_mux_icmp_ln556_phi_fu_202_p4 = icmp_ln55_reg_648;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_i5_load = 10'd0;
    end else begin
        ap_sig_allocacmp_i5_load = i5_fu_146;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten2_load = 15'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten2_load = indvar_flatten2_fu_134;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_or_i74_load = zext_ln52_fu_222_p1;
    end else begin
        ap_sig_allocacmp_or_i74_load = or_i74_fu_142;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (first_iter_0_reg_639 == 1'd1))) begin
        gmem_ARVALID = 1'b1;
    end else begin
        gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        gmem_AWVALID = 1'b1;
    end else begin
        gmem_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        gmem_BREADY = 1'b1;
    end else begin
        gmem_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        gmem_RREADY = 1'b1;
    end else begin
        gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        gmem_WVALID = 1'b1;
    end else begin
        gmem_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0) & (first_iter_0_reg_639 == 1'd1))) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem_blk_n_R = m_axi_gmem_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter14 == 1'b1) & (1'b0 == ap_block_pp0_stage0))) begin
        gmem_blk_n_W = m_axi_gmem_WREADY;
    end else begin
        gmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_210_ce = 1'b1;
    end else begin
        grp_fu_210_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_215_ce = 1'b1;
    end else begin
        grp_fu_215_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_218_ce = 1'b1;
    end else begin
        grp_fu_218_ce = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln54_1_fu_291_p2 = (ap_sig_allocacmp_indvar_flatten2_load + 15'd1);

assign add_ln54_fu_478_p2 = (t_fu_427_p3 + 5'd1);

assign add_ln62_1_fu_500_p2 = (zext_ln55_1_fu_497_p1 + spikes_read_reg_623_pp0_iter11_reg);

assign add_ln62_fu_505_p2 = (add_ln62_1_fu_500_p2 + zext_ln55_fu_494_p1);

assign and_ln62_1_fu_549_p2 = (tmp_2_reg_713 & and_ln62_fu_543_p2);

assign and_ln62_fu_543_p2 = (or_ln62_fu_535_p2 & or_ln62_1_fu_539_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_00001 = (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b1 == ap_block_state20_pp0_stage0_iter19)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage0_iter9)));
end

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b1 == ap_block_state20_pp0_stage0_iter19)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage0_iter9)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b1 == ap_block_state20_pp0_stage0_iter19)) | ((ap_enable_reg_pp0_iter14 == 1'b1) & (gmem_WREADY == 1'b0)) | ((gmem_AWREADY == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b1)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage0_iter9)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_io)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((ap_enable_reg_pp0_iter19 == 1'b1) & (1'b1 == ap_block_state20_pp0_stage0_iter19)) | ((ap_enable_reg_pp0_iter14 == 1'b1) & (gmem_WREADY == 1'b0)) | ((gmem_AWREADY == 1'b0) & (ap_enable_reg_pp0_iter13 == 1'b1)) | ((ap_enable_reg_pp0_iter9 == 1'b1) & (1'b1 == ap_block_state10_pp0_stage0_iter9)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_block_state2_io)));
end

always @ (*) begin
    ap_block_state10_pp0_stage0_iter9 = (gmem_RVALID == 1'b0);
end

always @ (*) begin
    ap_block_state20_pp0_stage0_iter19 = (gmem_BVALID == 1'b0);
end

always @ (*) begin
    ap_block_state2_io = ((first_iter_0_reg_639 == 1'd1) & (gmem_ARREADY == 1'b0));
end

always @ (*) begin
    ap_condition_361 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

always @ (*) begin
    ap_condition_535 = ((ap_loop_init == 1'b1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_856 = ((icmp_ln54_reg_653 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0));
end

always @ (*) begin
    ap_condition_862 = ((icmp_ln54_reg_653 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001));
end

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign bitcast_ln62_fu_449_p1 = rand_val_reg_677;

assign first_iter_0_fu_285_p2 = ((select_ln54_fu_277_p3 == 10'd0) ? 1'b1 : 1'b0);

assign gmem_ARLEN = 64'd784;

assign gmem_AWLEN = 64'd1;

assign gmem_WDATA = shl_ln62_2_reg_735;

assign grp_fu_218_p1 = gmem_addr_read_reg_662_pp0_iter10_reg;

assign i_fu_364_p2 = (select_ln54_fu_277_p3 + 10'd1);

assign icmp_ln54_fu_376_p2 = ((ap_sig_allocacmp_indvar_flatten2_load == 15'd19599) ? 1'b1 : 1'b0);

assign icmp_ln55_fu_370_p2 = ((i_fu_364_p2 == 10'd784) ? 1'b1 : 1'b0);

assign icmp_ln62_1_fu_472_p2 = ((trunc_ln62_fu_462_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln62_2_fu_411_p2 = ((tmp_1_reg_667 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln62_3_fu_416_p2 = ((trunc_ln62_2_reg_672 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln62_fu_466_p2 = ((tmp_fu_452_p4 != 8'd255) ? 1'b1 : 1'b0);

assign lshr_ln_fu_328_p4 = {{ap_sig_allocacmp_or_i74_load[31:1]}};

assign mul_ln55_fu_439_p0 = mul_ln55_fu_439_p00;

assign mul_ln55_fu_439_p00 = t_fu_427_p3;

assign mul_ln55_fu_439_p1 = 15'd784;

assign or_ln62_1_fu_539_p2 = (icmp_ln62_3_reg_688_pp0_iter12_reg | icmp_ln62_2_reg_683_pp0_iter12_reg);

assign or_ln62_fu_535_p2 = (icmp_ln62_reg_703_pp0_iter12_reg | icmp_ln62_1_reg_708_pp0_iter12_reg);

assign or_ln_fu_356_p3 = {{xor_ln18_fu_350_p2}, {lshr_ln_fu_328_p4}};

assign p_cast_cast_fu_236_p1 = $signed(p_cast_fu_226_p4);

assign p_cast_fu_226_p4 = {{img[63:2]}};

assign select_ln54_fu_277_p3 = ((ap_phi_mux_icmp_ln556_phi_fu_202_p4[0:0] == 1'b1) ? 10'd0 : ap_sig_allocacmp_i5_load);

assign sext_ln62_fu_525_p1 = $signed(trunc_ln62_1_fu_515_p4);

assign shl_ln62_1_fu_567_p3 = {{trunc_ln62_3_reg_718}, {3'd0}};

assign shl_ln62_2_fu_578_p2 = zext_ln62_fu_554_p1 << zext_ln62_2_fu_574_p1;

assign shl_ln62_fu_561_p2 = 4'd1 << zext_ln62_1_fu_558_p1;

assign t_fu_427_p3 = ((icmp_ln556_reg_199_pp0_iter10_reg[0:0] == 1'b1) ? add_ln547_fu_150 : t3_fu_138);

assign tmp_3_fu_304_p3 = ap_sig_allocacmp_or_i74_load[32'd3];

assign tmp_4_fu_312_p3 = ap_sig_allocacmp_or_i74_load[32'd2];

assign tmp_5_fu_320_p3 = ap_sig_allocacmp_or_i74_load[32'd5];

assign tmp_fu_452_p4 = {{bitcast_ln62_fu_449_p1[30:23]}};

assign trunc_ln17_fu_300_p1 = ap_sig_allocacmp_or_i74_load[0:0];

assign trunc_ln62_1_fu_515_p4 = {{add_ln62_fu_505_p2[63:2]}};

assign trunc_ln62_2_fu_407_p1 = gmem_RDATA[22:0];

assign trunc_ln62_3_fu_511_p1 = add_ln62_fu_505_p2[1:0];

assign trunc_ln62_fu_462_p1 = bitcast_ln62_fu_449_p1[22:0];

assign xor_ln18_1_fu_344_p2 = (xor_ln18_2_fu_338_p2 ^ tmp_3_fu_304_p3);

assign xor_ln18_2_fu_338_p2 = (tmp_5_fu_320_p3 ^ tmp_4_fu_312_p3);

assign xor_ln18_fu_350_p2 = (xor_ln18_1_fu_344_p2 ^ trunc_ln17_fu_300_p1);

assign zext_ln52_fu_222_p1 = seed;

assign zext_ln55_1_fu_497_p1 = select_ln54_reg_634_pp0_iter11_reg;

assign zext_ln55_fu_494_p1 = mul_ln55_reg_693;

assign zext_ln62_1_fu_558_p1 = trunc_ln62_3_reg_718;

assign zext_ln62_2_fu_574_p1 = shl_ln62_1_fu_567_p3;

assign zext_ln62_fu_554_p1 = and_ln62_1_fu_549_p2;

endmodule //rate_encoding
